-- Converted from ice_gate_to_business_rle.json
-- {n, buttons} RLE runs. Lua 5.1.
return {
  {14, {}},
  {7, {"RIGHT"}},
  {21, {"B", "RIGHT"}},
  {7, {"RIGHT"}},
  {12, {}},
  {8, {"DOWN"}},
  {9, {}},
  {11, {"DOWN"}},
  {5, {}},
  {31, {"RIGHT"}},
  {24, {}},
  {7, {"X"}},
  {5, {}},
  {5, {"X"}},
  {8, {}},
  {6, {"X"}},
  {7, {}},
  {6, {"X"}},
  {3, {}},
  {20, {"RIGHT"}},
  {8, {"RIGHT", "X"}},
  {4, {"RIGHT"}},
  {80, {"RIGHT"}},
  {11, {"RIGHT", "X"}},
  {198, {"RIGHT"}},
  {27, {}},
  {9, {"UP"}},
  {6, {}},
  {6, {"RIGHT"}},
  {9, {"RIGHT", "X"}},
  {23, {"RIGHT"}},
}
