-- KPDR room ids through Gravity / WS / Ice / Wave.
-- Names match snes/super_metroid/routes/kpdr/room_ids.py.

local rooms = {}

-- Ceres
rooms.ROOM_CERES_ELEVATOR = 0xDF45
rooms.ROOM_CERES_FALLING = 0xDF8D
rooms.ROOM_CERES_MAGNET = 0xDFD7
rooms.ROOM_CERES_SCIENTIST = 0xE021
rooms.ROOM_CERES_FLAT = 0xE06B
rooms.ROOM_CERES_RIDLEY = 0xE0B5

-- Crateria / early Brinstar
rooms.ROOM_LANDING_SITE = 0x91F8
rooms.ROOM_PARLOR = 0x92FD
rooms.ROOM_GAUNTLET_ENTRANCE = 0x92B3
rooms.ROOM_GAUNTLET_ETANK = 0x965B
rooms.ROOM_CLIMB = 0x96BA
rooms.ROOM_PIT = 0x975C
rooms.ROOM_BLUE_BRINSTAR_ELEVATOR = 0x97B5
rooms.ROOM_MORPH = 0x9E9F
rooms.ROOM_CONSTRUCTION = 0x9F11
rooms.ROOM_BLUE_BRINSTAR_ETANK = 0x9F64
rooms.ROOM_FIRST_MISSILE = 0xA107
rooms.ROOM_FLYWAY = 0x9879
rooms.ROOM_BOMB_TORIZO = 0x9804
rooms.ROOM_TERMINATOR = 0x990D
rooms.ROOM_GREEN_PIRATES = 0x99BD
rooms.ROOM_LOWER_MUSHROOMS = 0x9969
rooms.ROOM_GREEN_ELEVATOR = 0x9938
rooms.ROOM_GREEN_MAIN_SHAFT = 0x9AD9
rooms.ROOM_DACHORA = 0x9CB3
rooms.ROOM_SPORE_KIHUNTER = 0x9D9C
rooms.ROOM_SPORE_SPAWN = 0x9DC7

-- Spore Super → Pink Brinstar
rooms.ROOM_SUPER = 0x9B5B
rooms.ROOM_FARMING = 0xA0A4
rooms.ROOM_BIG_PINK = 0x9D19
rooms.ROOM_PINK_PB = 0x9E11

-- Brinstar → Kraid
rooms.ROOM_GHZ = 0x9E52
rooms.ROOM_NOOB = 0x9FBA
rooms.ROOM_RED_TOWER = 0xA253
rooms.ROOM_HELLWAY = 0xA2F7
rooms.ROOM_CATERPILLAR = 0xA322
rooms.ROOM_ALPHA_PB = 0xA3AE
rooms.ROOM_BAT = 0xA3DD
rooms.ROOM_BELOW_SPAZER = 0xA408
rooms.ROOM_SPAZER = 0xA447
rooms.ROOM_WEST_TUNNEL = 0xCF54
rooms.ROOM_GLASS = 0xCEFB
rooms.ROOM_EAST_TUNNEL = 0xCF80
rooms.ROOM_WAREHOUSE = 0xA6A1
rooms.ROOM_BUSINESS = 0xA7DE
rooms.ROOM_HJ_SHAFT = 0xAA41
rooms.ROOM_HJ = 0xA9E5
rooms.ROOM_ZEELA = 0xA471
rooms.ROOM_WAREHOUSE_KIHUNTER = 0xA4DA
rooms.ROOM_BABY_KRAID = 0xA521
rooms.ROOM_KRAID_EYE = 0xA56B
rooms.ROOM_KRAID = 0xA59F
rooms.ROOM_VARIA = 0xA6E2

-- Norfair: Cathedral / Speed / Wave / Ice
rooms.ROOM_FROG_SAVE = 0xB167
rooms.ROOM_FROG_SPEEDWAY = 0xB106
rooms.ROOM_UPPER_NORFAIR_FARM = 0xAF72
rooms.ROOM_CATHEDRAL_ENTRANCE = 0xA7B3
rooms.ROOM_CATHEDRAL = 0xA788
rooms.ROOM_RISING_TIDE = 0xAFA3
rooms.ROOM_BUBBLE = 0xACB3
rooms.ROOM_BAT_CAVE = 0xB07A
rooms.ROOM_SPEED_HALL = 0xACF0
rooms.ROOM_SPEED = 0xAD1B
rooms.ROOM_SINGLE_CHAMBER = 0xAD5E
rooms.ROOM_DOUBLE_CHAMBER = 0xADAD
rooms.ROOM_WAVE = 0xADDE
rooms.ROOM_ICE_GATE = 0xA815
rooms.ROOM_ICE_ACID = 0xA75D
rooms.ROOM_ICE_TUTORIAL = 0xA865
rooms.ROOM_ICE_SNAKE = 0xA8B9
rooms.ROOM_ICE = 0xA890

-- Crateria → Wrecked Ship → Gravity
rooms.ROOM_RED_BRINSTAR_ELEVATOR = 0x962A
rooms.ROOM_CRATERIA_KIHUNTER = 0x948C
rooms.ROOM_MOAT = 0x95FF
rooms.ROOM_WEST_OCEAN = 0x93FE
rooms.ROOM_PANCAKES = 0x9461
rooms.ROOM_HOMING_GEEMER = 0x968F
rooms.ROOM_BOWLING = 0xC98E
rooms.ROOM_WS_ENTRANCE = 0xCA08
rooms.ROOM_WS_MAIN = 0xCAF6
rooms.ROOM_WS_ATTIC = 0xCA52
rooms.ROOM_WS_BASEMENT = 0xCC6F
rooms.ROOM_WS_MAP = 0xCCCB
rooms.ROOM_WS_WEST_SUPER = 0xCDA8
rooms.ROOM_WS_SAVE = 0xCE8A
rooms.ROOM_WS_SPONGE = 0xCD5C
rooms.ROOM_PHANTOON = 0xCD13
rooms.ROOM_GRAVITY = 0xCE40

return rooms
