"""KPDR pure-controller segments (full continuous spine after power-on).

Includes Spore Super collect → Big Pink through Hi-Jump and Kraid entry.
Import from ``super_metroid.routes.kpdr`` (historical ``kpdr_controller`` /
``post_spore_controller`` shims are deleted).

Exports load lazily so ``room_ids`` (pure constants) can be imported from
``progression`` without pulling ``controller_common`` / ``runtime``.
"""

from __future__ import annotations

from typing import Any

__all__ = [
    "ITEM_HI_JUMP",
    "KPDR_SEGMENTS",
    "MORPH_POSES",
    "MorphBombRollPhase",
    "PowerBombEvidence",
    "ROOM_BABY_KRAID",
    "ROOM_BAT",
    "ROOM_BELOW_SPAZER",
    "ROOM_BIG_PINK",
    "ROOM_BUSINESS",
    "ROOM_EAST_TUNNEL",
    "ROOM_FARMING",
    "ROOM_GHZ",
    "ROOM_GLASS",
    "ROOM_HJ",
    "ROOM_HJ_SHAFT",
    "ROOM_KRAID",
    "ROOM_KRAID_EYE",
    "ROOM_NOOB",
    "ROOM_PINK_PB",
    "ROOM_RED_TOWER",
    "ROOM_SUPER",
    "ROOM_VARIA",
    "ROOM_WAREHOUSE",
    "ROOM_WAREHOUSE_KIHUNTER",
    "ROOM_WEST_TUNNEL",
    "ROOM_ZEELA",
    "SuperCollectEvidence",
    "bomb_roll_left_safe",
    "ensure_morph",
    "get_segment",
    "is_morph",
    "play_baby_kraid_to_eye",
    "play_bat_cave_to_speed_hall",
    "play_speed_hall_to_speed",
    "play_speed_return_to_bubble",
    "play_bubble_to_single_chamber",
    "play_single_to_double_chamber",
    "play_double_chamber_to_wave",
    "play_wave_to_double_chamber",
    "play_double_to_single_chamber",
    "play_single_to_bubble",
    "play_bubble_to_farm",
    "play_farm_to_speedway",
    "play_speedway_to_frog_save",
    "play_bat_to_below_spazer",
    "play_below_spazer_to_west",
    "play_big_pink_bomb_to_walkway_edge",
    "play_big_pink_clear_super_block",
    "play_big_pink_crest_pocket",
    "play_big_pink_drop_to_pocket",
    "play_big_pink_enter_pb_door_from_sill",
    "play_big_pink_enter_pb_door_from_top_ledge",
    "play_big_pink_into_main_shaft",
    "play_big_pink_morph_to_tunnel",
    "play_big_pink_to_ghz",
    "play_big_pink_tunnel_west",
    "play_business_to_hj_shaft",
    "play_business_to_frog_save",
    "play_business_to_ice_gate",
    "play_ice_gate_to_acid",
    "play_ice_acid_to_snake",
    "play_ice_snake_to_ice",
    "play_business_to_warehouse",
    "play_east_to_warehouse",
    "play_eye_to_kraid",
    "play_eye_to_baby_return",
    "play_kraid_entry_to_varia",
    "play_kraid_to_eye_return",
    "play_farming_to_big_pink",
    "play_frog_save_to_speedway",
    "play_speedway_to_farm",
    "play_ghz_to_noob",
    "play_glass_to_east",
    "play_hijump_to_warehouse",
    "play_hj_room_collect",
    "play_hj_room_to_shaft",
    "play_hj_shaft_to_business",
    "play_hj_shaft_to_hj_room",
    "play_kihunter_to_baby_kraid",
    "play_kihunter_to_zeela_return",
    "play_noob_to_red_tower",
    "play_pink_pb_break_maze_wall",
    "play_pink_pb_from_left_zone",
    "play_pink_pb_mid_maze_to_collect",
    "play_pink_pb_morph_bomb_collect",
    "play_post_spore_supers",
    "play_red_tower_to_bat",
    "play_red_tower_to_warehouse",
    "play_run_shoot_exit",
    "play_super_room_collect",
    "play_super_room_to_farming",
    "play_varia_to_kraid",
    "play_baby_to_kihunter_return",
    "play_warehouse_hijump_kraid",
    "play_warehouse_to_business",
    "play_warehouse_to_hijump",
    "play_warehouse_to_kraid_with_hijump",
    "play_warehouse_to_zeela_with_hijump",
    "play_warehouse_wall_to_lower_lip",
    "play_west_to_glass",
    "play_zeela_to_kihunter",
    "play_zeela_to_warehouse_return",
    "wait_until",
]

# export_name -> (module, attr)
_EXPORTS: dict[str, tuple[str, str]] = {
    "ITEM_HI_JUMP": ("super_metroid.routes.kpdr.rooms", "ITEM_HI_JUMP"),
    "KPDR_SEGMENTS": ("super_metroid.routes.kpdr.registry", "KPDR_SEGMENTS"),
    "MORPH_POSES": ("super_metroid.routes.controller_common", "MORPH_POSES"),
    "MorphBombRollPhase": ("super_metroid.routes.kpdr.morph_bomb_roll", "MorphBombRollPhase"),
    "PowerBombEvidence": ("super_metroid.routes.kpdr.rooms", "PowerBombEvidence"),
    "ROOM_BABY_KRAID": ("super_metroid.routes.kpdr.rooms", "ROOM_BABY_KRAID"),
    "ROOM_BAT": ("super_metroid.routes.kpdr.rooms", "ROOM_BAT"),
    "ROOM_BELOW_SPAZER": ("super_metroid.routes.kpdr.rooms", "ROOM_BELOW_SPAZER"),
    "ROOM_BIG_PINK": ("super_metroid.routes.kpdr.rooms", "ROOM_BIG_PINK"),
    "ROOM_BUSINESS": ("super_metroid.routes.kpdr.rooms", "ROOM_BUSINESS"),
    "ROOM_EAST_TUNNEL": ("super_metroid.routes.kpdr.rooms", "ROOM_EAST_TUNNEL"),
    "ROOM_FARMING": ("super_metroid.routes.kpdr.rooms", "ROOM_FARMING"),
    "ROOM_GHZ": ("super_metroid.routes.kpdr.rooms", "ROOM_GHZ"),
    "ROOM_GLASS": ("super_metroid.routes.kpdr.rooms", "ROOM_GLASS"),
    "ROOM_HJ": ("super_metroid.routes.kpdr.rooms", "ROOM_HJ"),
    "ROOM_HJ_SHAFT": ("super_metroid.routes.kpdr.rooms", "ROOM_HJ_SHAFT"),
    "ROOM_KRAID": ("super_metroid.routes.kpdr.rooms", "ROOM_KRAID"),
    "ROOM_KRAID_EYE": ("super_metroid.routes.kpdr.rooms", "ROOM_KRAID_EYE"),
    "ROOM_NOOB": ("super_metroid.routes.kpdr.rooms", "ROOM_NOOB"),
    "ROOM_PINK_PB": ("super_metroid.routes.kpdr.rooms", "ROOM_PINK_PB"),
    "ROOM_RED_TOWER": ("super_metroid.routes.kpdr.rooms", "ROOM_RED_TOWER"),
    "ROOM_SUPER": ("super_metroid.routes.kpdr.rooms", "ROOM_SUPER"),
    "ROOM_VARIA": ("super_metroid.routes.kpdr.rooms", "ROOM_VARIA"),
    "ROOM_WAREHOUSE": ("super_metroid.routes.kpdr.rooms", "ROOM_WAREHOUSE"),
    "ROOM_WAREHOUSE_KIHUNTER": ("super_metroid.routes.kpdr.rooms", "ROOM_WAREHOUSE_KIHUNTER"),
    "ROOM_WEST_TUNNEL": ("super_metroid.routes.kpdr.rooms", "ROOM_WEST_TUNNEL"),
    "ROOM_ZEELA": ("super_metroid.routes.kpdr.rooms", "ROOM_ZEELA"),
    "SuperCollectEvidence": ("super_metroid.routes.kpdr.rooms", "SuperCollectEvidence"),
    "bomb_roll_left_safe": ("super_metroid.routes.kpdr.morph_bomb_roll", "bomb_roll_left_safe"),
    "ensure_morph": ("super_metroid.routes.controller_common", "ensure_morph"),
    "get_segment": ("super_metroid.routes.kpdr.registry", "get_segment"),
    "is_morph": ("super_metroid.routes.controller_common", "is_morph"),
    "play_baby_kraid_to_eye": ("super_metroid.routes.kpdr.to_kraid", "play_baby_kraid_to_eye"),
    "play_baby_to_kihunter_return": ("super_metroid.routes.kpdr.from_kraid", "play_baby_to_kihunter_return"),
    "play_bat_cave_to_speed_hall": ("super_metroid.routes.kpdr.k4_norfair", "play_bat_cave_to_speed_hall"),
    "play_speed_hall_to_speed": ("super_metroid.routes.kpdr.k4_norfair", "play_speed_hall_to_speed"),
    "play_speed_return_to_bubble": ("super_metroid.routes.kpdr.k4_norfair", "play_speed_return_to_bubble"),
    "play_bubble_to_single_chamber": ("super_metroid.routes.kpdr.k4_norfair", "play_bubble_to_single_chamber"),
    "play_single_to_double_chamber": ("super_metroid.routes.kpdr.k4_norfair", "play_single_to_double_chamber"),
    "play_double_chamber_to_wave": ("super_metroid.routes.kpdr.k4_norfair", "play_double_chamber_to_wave"),
    "play_wave_to_double_chamber": ("super_metroid.routes.kpdr.k4_norfair", "play_wave_to_double_chamber"),
    "play_double_to_single_chamber": ("super_metroid.routes.kpdr.k4_norfair", "play_double_to_single_chamber"),
    "play_single_to_bubble": ("super_metroid.routes.kpdr.k4_norfair", "play_single_to_bubble"),
    "play_bubble_to_farm": ("super_metroid.routes.kpdr.k4_norfair", "play_bubble_to_farm"),
    "play_farm_to_speedway": ("super_metroid.routes.kpdr.k4_norfair", "play_farm_to_speedway"),
    "play_speedway_to_frog_save": ("super_metroid.routes.kpdr.k4_norfair", "play_speedway_to_frog_save"),
    "play_bat_to_below_spazer": ("super_metroid.routes.kpdr.red_stack", "play_bat_to_below_spazer"),
    "play_below_spazer_to_west": ("super_metroid.routes.kpdr.red_stack", "play_below_spazer_to_west"),
    "play_big_pink_bomb_to_walkway_edge": ("super_metroid.routes.kpdr.pink_shaft", "play_big_pink_bomb_to_walkway_edge"),
    "play_big_pink_clear_super_block": ("super_metroid.routes.kpdr.pink_shaft", "play_big_pink_clear_super_block"),
    "play_big_pink_crest_pocket": ("super_metroid.routes.kpdr.pink_shaft", "play_big_pink_crest_pocket"),
    "play_big_pink_drop_to_pocket": ("super_metroid.routes.kpdr.pink_shaft", "play_big_pink_drop_to_pocket"),
    "play_big_pink_enter_pb_door_from_sill": ("super_metroid.routes.kpdr.pb_door", "play_big_pink_enter_pb_door_from_sill"),
    "play_big_pink_enter_pb_door_from_top_ledge": ("super_metroid.routes.kpdr.pb_door", "play_big_pink_enter_pb_door_from_top_ledge"),
    "play_big_pink_into_main_shaft": ("super_metroid.routes.kpdr.pink_shaft", "play_big_pink_into_main_shaft"),
    "play_big_pink_morph_to_tunnel": ("super_metroid.routes.kpdr.pink_shaft", "play_big_pink_morph_to_tunnel"),
    "play_big_pink_to_ghz": ("super_metroid.routes.kpdr.pink_to_ghz", "play_big_pink_to_ghz"),
    "play_big_pink_tunnel_west": ("super_metroid.routes.kpdr.pink_shaft", "play_big_pink_tunnel_west"),
    "play_business_to_frog_save": ("super_metroid.routes.kpdr.k4_norfair", "play_business_to_frog_save"),
    "play_business_to_hj_shaft": ("super_metroid.routes.kpdr.hijump", "play_business_to_hj_shaft"),
    "play_business_to_ice_gate": ("super_metroid.routes.kpdr.ice", "play_business_to_ice_gate"),
    "play_ice_gate_to_acid": ("super_metroid.routes.kpdr.ice", "play_ice_gate_to_acid"),
    "play_ice_acid_to_snake": ("super_metroid.routes.kpdr.ice", "play_ice_acid_to_snake"),
    "play_ice_snake_to_ice": ("super_metroid.routes.kpdr.ice", "play_ice_snake_to_ice"),
    "play_business_to_warehouse": ("super_metroid.routes.kpdr.hijump", "play_business_to_warehouse"),
    "play_east_to_warehouse": ("super_metroid.routes.kpdr.red_stack", "play_east_to_warehouse"),
    "play_eye_to_baby_return": ("super_metroid.routes.kpdr.from_kraid", "play_eye_to_baby_return"),
    "play_eye_to_kraid": ("super_metroid.routes.kpdr.to_kraid", "play_eye_to_kraid"),
    "play_farming_to_big_pink": ("super_metroid.routes.kpdr.super_collect", "play_farming_to_big_pink"),
    "play_frog_save_to_speedway": ("super_metroid.routes.kpdr.k4_norfair", "play_frog_save_to_speedway"),
    "play_ghz_to_noob": ("super_metroid.routes.kpdr.ghz_to_red", "play_ghz_to_noob"),
    "play_glass_to_east": ("super_metroid.routes.kpdr.red_stack", "play_glass_to_east"),
    "play_hijump_to_warehouse": ("super_metroid.routes.kpdr.hijump", "play_hijump_to_warehouse"),
    "play_hj_room_collect": ("super_metroid.routes.kpdr.hijump", "play_hj_room_collect"),
    "play_hj_room_to_shaft": ("super_metroid.routes.kpdr.hijump", "play_hj_room_to_shaft"),
    "play_hj_shaft_to_business": ("super_metroid.routes.kpdr.hijump", "play_hj_shaft_to_business"),
    "play_hj_shaft_to_hj_room": ("super_metroid.routes.kpdr.hijump", "play_hj_shaft_to_hj_room"),
    "play_kihunter_to_baby_kraid": ("super_metroid.routes.kpdr.to_kraid", "play_kihunter_to_baby_kraid"),
    "play_kihunter_to_zeela_return": ("super_metroid.routes.kpdr.from_kraid", "play_kihunter_to_zeela_return"),
    "play_kraid_entry_to_varia": ("super_metroid.routes.kpdr.to_kraid", "play_kraid_entry_to_varia"),
    "play_kraid_to_eye_return": ("super_metroid.routes.kpdr.varia_return", "play_kraid_to_eye_return"),
    "play_noob_to_red_tower": ("super_metroid.routes.kpdr.ghz_to_red", "play_noob_to_red_tower"),
    "play_pink_pb_break_maze_wall": ("super_metroid.routes.kpdr.pink_pb", "play_pink_pb_break_maze_wall"),
    "play_pink_pb_from_left_zone": ("super_metroid.routes.kpdr.pink_pb", "play_pink_pb_from_left_zone"),
    "play_pink_pb_mid_maze_to_collect": ("super_metroid.routes.kpdr.pink_pb", "play_pink_pb_mid_maze_to_collect"),
    "play_pink_pb_morph_bomb_collect": ("super_metroid.routes.kpdr.pink_pb", "play_pink_pb_morph_bomb_collect"),
    "play_post_spore_supers": ("super_metroid.routes.kpdr.super_collect", "play_post_spore_supers"),
    "play_red_tower_to_bat": ("super_metroid.routes.kpdr.red_stack", "play_red_tower_to_bat"),
    "play_red_tower_to_warehouse": ("super_metroid.routes.kpdr.red_stack", "play_red_tower_to_warehouse"),
    "play_run_shoot_exit": ("super_metroid.routes.controller_common", "play_run_shoot_exit"),
    "play_speedway_to_farm": ("super_metroid.routes.kpdr.k4_norfair", "play_speedway_to_farm"),
    "play_super_room_collect": ("super_metroid.routes.kpdr.super_collect", "play_super_room_collect"),
    "play_super_room_to_farming": ("super_metroid.routes.kpdr.super_collect", "play_super_room_to_farming"),
    "play_varia_to_kraid": ("super_metroid.routes.kpdr.varia_return", "play_varia_to_kraid"),
    "play_warehouse_hijump_kraid": ("super_metroid.routes.kpdr.to_kraid", "play_warehouse_hijump_kraid"),
    "play_warehouse_to_business": ("super_metroid.routes.kpdr.warehouse_stack", "play_warehouse_to_business"),
    "play_warehouse_to_hijump": ("super_metroid.routes.kpdr.hijump", "play_warehouse_to_hijump"),
    "play_warehouse_to_kraid_with_hijump": ("super_metroid.routes.kpdr.to_kraid", "play_warehouse_to_kraid_with_hijump"),
    "play_warehouse_to_zeela_with_hijump": ("super_metroid.routes.kpdr.to_kraid", "play_warehouse_to_zeela_with_hijump"),
    "play_warehouse_wall_to_lower_lip": ("super_metroid.routes.kpdr.warehouse_stack", "play_warehouse_wall_to_lower_lip"),
    "play_west_to_glass": ("super_metroid.routes.kpdr.red_stack", "play_west_to_glass"),
    "play_zeela_to_kihunter": ("super_metroid.routes.kpdr.to_kraid", "play_zeela_to_kihunter"),
    "play_zeela_to_warehouse_return": ("super_metroid.routes.kpdr.from_kraid", "play_zeela_to_warehouse_return"),
    "wait_until": ("super_metroid.routes.controller_common", "wait_until"),
}


def __getattr__(name: str) -> Any:
    try:
        module_name, attr = _EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(
            f"module {__name__!r} has no attribute {name!r}"
        ) from exc
    import importlib

    module = importlib.import_module(module_name)
    value = getattr(module, attr)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
