"""Post-Ice continuous spine hops (K5 Alpha PB + K6 Moat + WS spark).

Appended onto :data:`POST_SUPERS_SPINE`. Door meta is omitted only for the
Business→Warehouse replay (edge already emitted on the Kraid tip).
"""

from __future__ import annotations

from super_metroid.routes.kpdr.hijump import play_business_to_warehouse
from super_metroid.routes.kpdr.ice import (
    play_ice_gate_to_business,
    play_ice_snake_to_tutorial,
    play_ice_to_snake,
    play_ice_tutorial_to_gate,
)
from super_metroid.routes.kpdr.k5 import (
    play_bat_to_red,
    play_below_to_bat,
    play_caterpillar_to_alpha_pb,
    play_east_to_glass,
    play_glass_to_west,
    play_hellway_to_caterpillar,
    play_red_to_hellway,
    play_warehouse_to_east,
    play_west_to_below,
)
from super_metroid.routes.kpdr.k6 import (
    play_alpha_pb_to_caterpillar,
    play_caterpillar_to_elevator,
    play_elevator_to_kihunter,
    play_kihunter_to_moat,
    play_phantoon_loot_exit,
    play_phantoon_room_fight,
    play_ws_basement_to_phantoon,
    play_ws_entrance_to_main,
    play_ws_main_to_basement,
)
from super_metroid.routes.kpdr.k6.phantoon_fight import require_phantoon_defeated
from super_metroid.routes.kpdr.k6.phantoon_leave import require_phantoon_left
from super_metroid.routes.kpdr.moat import play_moat_cross
from super_metroid.routes.kpdr.west_ocean import play_west_ocean_over_ocean_spark
from super_metroid.routes.kpdr.rooms import (
    ROOM_ALPHA_PB,
    ROOM_BAT,
    ROOM_BELOW_SPAZER,
    ROOM_BUSINESS,
    ROOM_CATERPILLAR,
    ROOM_CRATERIA_KIHUNTER,
    ROOM_EAST_TUNNEL,
    ROOM_GLASS,
    ROOM_HELLWAY,
    ROOM_ICE,
    ROOM_ICE_GATE,
    ROOM_ICE_SNAKE,
    ROOM_ICE_TUTORIAL,
    ROOM_MOAT,
    ROOM_PHANTOON,
    ROOM_RED_BRINSTAR_ELEVATOR,
    ROOM_RED_TOWER,
    ROOM_WAREHOUSE,
    ROOM_WEST_OCEAN,
    ROOM_WEST_TUNNEL,
    ROOM_WS_BASEMENT,
    ROOM_WS_ENTRANCE,
    ROOM_WS_MAIN,
)
from super_metroid.routes.kpdr.spine_types import K4_CAPS, SpineHop
from super_metroid.routes.runtime import RouteSession

_K4_SPEED_CAPS = K4_CAPS | frozenset({"speed_booster"})

__all__ = ["POST_ICE_SPINE"]


def _require_alpha_pb_collected(
    session: RouteSession, splits: list, result: object = None
) -> None:
    del splits, result
    if int(session.state.max_power_bombs) < 5:
        raise RuntimeError(
            "Alpha PB not collected: "
            f"max_power_bombs={session.state.max_power_bombs}"
        )


POST_ICE_SPINE: tuple[SpineHop, ...] = (
    SpineHop(
        "ice_to_snake",
        play_ice_to_snake,
        ROOM_ICE,
        ROOM_ICE_SNAKE,
        "Ice Snake (Ice return)",
        "alpha_pb",
        exit_direction="left",
        entry_direction="right",
        requires=K4_CAPS,
        policy_id="kpdr_k5_alpha_pb",
    ),
    SpineHop(
        "ice_snake_to_tutorial",
        play_ice_snake_to_tutorial,
        ROOM_ICE_SNAKE,
        ROOM_ICE_TUTORIAL,
        "Ice Tutorial (Ice return)",
        "alpha_pb",
        exit_direction="right",
        entry_direction="left",
        requires=K4_CAPS,
        policy_id="kpdr_k5_alpha_pb",
    ),
    SpineHop(
        "ice_tutorial_to_gate",
        play_ice_tutorial_to_gate,
        ROOM_ICE_TUTORIAL,
        ROOM_ICE_GATE,
        "Ice Gate (Ice return)",
        "alpha_pb",
        exit_direction="right",
        entry_direction="left",
        requires=K4_CAPS,
        policy_id="kpdr_k5_alpha_pb",
    ),
    SpineHop(
        "ice_gate_to_business",
        play_ice_gate_to_business,
        ROOM_ICE_GATE,
        ROOM_BUSINESS,
        "Business Center (Ice return)",
        "alpha_pb",
        exit_direction="right",
        entry_direction="left",
        requires=K4_CAPS,
        policy_id="kpdr_k5_alpha_pb",
    ),
    SpineHop(
        "ice_business_to_warehouse",
        play_business_to_warehouse,
        ROOM_BUSINESS,
        ROOM_WAREHOUSE,
        "Warehouse (Ice return)",
        "alpha_pb",
        # Reuses kraid-tip business_to_warehouse DoorEdge.
    ),
    SpineHop(
        "warehouse_to_east",
        play_warehouse_to_east,
        ROOM_WAREHOUSE,
        ROOM_EAST_TUNNEL,
        "East Tunnel (K5 reverse)",
        "alpha_pb",
        exit_direction="left",
        entry_direction="right",
        requires=K4_CAPS,
        policy_id="kpdr_k5_alpha_pb",
    ),
    SpineHop(
        "east_to_glass",
        play_east_to_glass,
        ROOM_EAST_TUNNEL,
        ROOM_GLASS,
        "Glass Tunnel (K5 reverse)",
        "alpha_pb",
        exit_direction="left",
        entry_direction="right",
        requires=K4_CAPS,
        policy_id="kpdr_k5_alpha_pb",
    ),
    SpineHop(
        "glass_to_west",
        play_glass_to_west,
        ROOM_GLASS,
        ROOM_WEST_TUNNEL,
        "West Tunnel (K5 reverse)",
        "alpha_pb",
        exit_direction="left",
        entry_direction="right",
        requires=K4_CAPS,
        policy_id="kpdr_k5_alpha_pb",
    ),
    SpineHop(
        "west_to_below",
        play_west_to_below,
        ROOM_WEST_TUNNEL,
        ROOM_BELOW_SPAZER,
        "Below Spazer (K5 reverse)",
        "alpha_pb",
        exit_direction="left",
        entry_direction="right",
        requires=K4_CAPS,
        policy_id="kpdr_k5_alpha_pb",
    ),
    SpineHop(
        "below_to_bat",
        play_below_to_bat,
        ROOM_BELOW_SPAZER,
        ROOM_BAT,
        "Bat Room (K5 reverse)",
        "alpha_pb",
        exit_direction="left",
        entry_direction="right",
        requires=K4_CAPS,
        policy_id="kpdr_k5_alpha_pb",
    ),
    SpineHop(
        "bat_to_red",
        play_bat_to_red,
        ROOM_BAT,
        ROOM_RED_TOWER,
        "Red Tower bottom (K5 reverse)",
        "alpha_pb",
        exit_direction="left",
        entry_direction="right",
        requires=K4_CAPS,
        policy_id="kpdr_k5_alpha_pb",
    ),
    SpineHop(
        "red_to_hellway",
        play_red_to_hellway,
        ROOM_RED_TOWER,
        ROOM_HELLWAY,
        "Hellway",
        "alpha_pb",
        exit_direction="right",
        entry_direction="left",
        requires=K4_CAPS,
        policy_id="kpdr_k5_alpha_pb",
    ),
    SpineHop(
        "hellway_to_caterpillar",
        play_hellway_to_caterpillar,
        ROOM_HELLWAY,
        ROOM_CATERPILLAR,
        "Caterpillar Room",
        "alpha_pb",
        exit_direction="right",
        entry_direction="left",
        requires=K4_CAPS,
        policy_id="kpdr_k5_alpha_pb",
    ),
    SpineHop(
        "caterpillar_to_alpha_pb",
        play_caterpillar_to_alpha_pb,
        ROOM_CATERPILLAR,
        ROOM_ALPHA_PB,
        "Alpha Power Bomb Room",
        "alpha_pb",
        after=_require_alpha_pb_collected,
        exit_direction="right",
        entry_direction="left",
        requires=K4_CAPS,
        policy_id="kpdr_k5_alpha_pb",
    ),
    SpineHop(
        "alpha_pb_to_caterpillar",
        play_alpha_pb_to_caterpillar,
        ROOM_ALPHA_PB,
        ROOM_CATERPILLAR,
        "Caterpillar (Alpha PB return)",
        "moat",
        exit_direction="left",
        entry_direction="right",
        requires=K4_CAPS,
        policy_id="kpdr_k6_moat",
    ),
    SpineHop(
        "caterpillar_to_elevator",
        play_caterpillar_to_elevator,
        ROOM_CATERPILLAR,
        ROOM_RED_BRINSTAR_ELEVATOR,
        "Red Brinstar Elevator",
        "moat",
        exit_direction="up",
        entry_direction="down",
        requires=K4_CAPS,
        policy_id="kpdr_k6_moat",
    ),
    SpineHop(
        "elevator_to_kihunter",
        play_elevator_to_kihunter,
        ROOM_RED_BRINSTAR_ELEVATOR,
        ROOM_CRATERIA_KIHUNTER,
        "Crateria Kihunter",
        "moat",
        exit_direction="up",
        entry_direction="down",
        requires=K4_CAPS,
        policy_id="kpdr_k6_moat",
    ),
    SpineHop(
        "kihunter_to_moat",
        play_kihunter_to_moat,
        ROOM_CRATERIA_KIHUNTER,
        ROOM_MOAT,
        "The Moat",
        "moat",
        exit_direction="left",
        entry_direction="right",
        requires=K4_CAPS,
        policy_id="kpdr_k6_moat",
    ),
    SpineHop(
        "moat_cross",
        play_moat_cross,
        ROOM_MOAT,
        ROOM_WEST_OCEAN,
        "West Ocean (Moat spark)",
        "moat",
        exit_direction="left",
        entry_direction="right",
        requires=_K4_SPEED_CAPS,
        policy_id="kpdr_k6_moat",
    ),
    SpineHop(
        "west_ocean_to_ws",
        play_west_ocean_over_ocean_spark,
        ROOM_WEST_OCEAN,
        ROOM_WS_ENTRANCE,
        "Wrecked Ship Entrance (over-ocean spark)",
        "ws",
        exit_direction="right",
        entry_direction="left",
        requires=_K4_SPEED_CAPS,
        policy_id="kpdr_k6_ws",
    ),
    SpineHop(
        "ws_entrance_to_main",
        play_ws_entrance_to_main,
        ROOM_WS_ENTRANCE,
        ROOM_WS_MAIN,
        "Wrecked Ship Main Shaft",
        "phantoon",
        exit_direction="right",
        entry_direction="left",
        requires=K4_CAPS,
        policy_id="kpdr_k6_phantoon",
    ),
    SpineHop(
        "ws_main_to_basement",
        play_ws_main_to_basement,
        ROOM_WS_MAIN,
        ROOM_WS_BASEMENT,
        "Wrecked Ship Basement",
        "phantoon",
        exit_direction="down",
        entry_direction="up",
        requires=K4_CAPS,
        policy_id="kpdr_k6_phantoon",
    ),
    SpineHop(
        "ws_basement_to_phantoon",
        play_ws_basement_to_phantoon,
        ROOM_WS_BASEMENT,
        ROOM_PHANTOON,
        "Phantoon's Room",
        "phantoon",
        exit_direction="right",
        entry_direction="left",
        requires=K4_CAPS,
        policy_id="kpdr_k6_phantoon",
    ),
    SpineHop(
        "phantoon_fight",
        play_phantoon_room_fight,
        ROOM_PHANTOON,
        ROOM_PHANTOON,
        "Phantoon defeated",
        "phantoon",
        use_transition_split=False,
        after=require_phantoon_defeated,
        requires=K4_CAPS,
        policy_id="kpdr_k6_phantoon",
    ),
    SpineHop(
        "phantoon_loot_exit",
        play_phantoon_loot_exit,
        ROOM_PHANTOON,
        ROOM_WS_BASEMENT,
        "WS Basement (post-Phantoon)",
        "phantoon",
        exit_direction="left",
        entry_direction="right",
        after=require_phantoon_left,
        requires=K4_CAPS,
        policy_id="kpdr_k6_phantoon",
    ),
)
