"""Pure KPDR / progression room id constants (cycle-free).

No runtime, controller_common, SuperMetroidState, or progression imports.
``rooms.py`` re-exports these for back-compat; ``progression/stages/*`` import
from here so graph tables share one source of truth without circular imports.
"""

from __future__ import annotations

# --- Ceres (early graph only) ---
ROOM_CERES_ELEVATOR = 0xDF45
ROOM_CERES_FALLING = 0xDF8D
ROOM_CERES_MAGNET = 0xDFD7
ROOM_CERES_SCIENTIST = 0xE021
ROOM_CERES_FLAT = 0xE06B
ROOM_CERES_RIDLEY = 0xE0B5

# --- Crateria / early Brinstar (morph → bombs → spore path) ---
ROOM_LANDING_SITE = 0x91F8
ROOM_PARLOR = 0x92FD
ROOM_CLIMB = 0x96BA
ROOM_PIT = 0x975C
ROOM_BLUE_BRINSTAR_ELEVATOR = 0x97B5
ROOM_MORPH = 0x9E9F
ROOM_CONSTRUCTION = 0x9F11
ROOM_BLUE_BRINSTAR_ETANK = 0x9F64
ROOM_FIRST_MISSILE = 0xA107
ROOM_FLYWAY = 0x9879
ROOM_BOMB_TORIZO = 0x9804
ROOM_TERMINATOR = 0x990D
ROOM_GREEN_PIRATES = 0x99BD
ROOM_LOWER_MUSHROOMS = 0x9969
ROOM_GREEN_ELEVATOR = 0x9938
ROOM_GREEN_MAIN_SHAFT = 0x9AD9
ROOM_DACHORA = 0x9CB3
ROOM_SPORE_KIHUNTER = 0x9D9C
ROOM_SPORE_SPAWN = 0x9DC7

# K0 suffix / K1 prefix (Spore Super → Pink Brinstar)
ROOM_SUPER = 0x9B5B
ROOM_FARMING = 0xA0A4
ROOM_BIG_PINK = 0x9D19
ROOM_PINK_PB = 0x9E11

# K1–K2 Brinstar → Kraid
ROOM_GHZ = 0x9E52
ROOM_NOOB = 0x9FBA
ROOM_RED_TOWER = 0xA253
ROOM_HELLWAY = 0xA2F7
ROOM_CATERPILLAR = 0xA322
ROOM_ALPHA_PB = 0xA3AE
ROOM_BAT = 0xA3DD
ROOM_BELOW_SPAZER = 0xA408
ROOM_SPAZER = 0xA447
ROOM_WEST_TUNNEL = 0xCF54
ROOM_GLASS = 0xCEFB
ROOM_EAST_TUNNEL = 0xCF80
ROOM_WAREHOUSE = 0xA6A1
ROOM_BUSINESS = 0xA7DE
ROOM_HJ_SHAFT = 0xAA41
ROOM_HJ = 0xA9E5
ROOM_ZEELA = 0xA471
ROOM_WAREHOUSE_KIHUNTER = 0xA4DA
ROOM_BABY_KRAID = 0xA521
ROOM_KRAID_EYE = 0xA56B
ROOM_KRAID = 0xA59F
ROOM_VARIA = 0xA6E2

# K4: Varia return → Business → Bubble Mountain → Speed / Wave / Ice
# First Bubble visit is Cathedral climb (no Speed). Frog Speedway is post-Speed.
ROOM_FROG_SAVE = 0xB167
ROOM_FROG_SPEEDWAY = 0xB106
ROOM_UPPER_NORFAIR_FARM = 0xAF72
ROOM_CATHEDRAL_ENTRANCE = 0xA7B3
ROOM_CATHEDRAL = 0xA788
ROOM_RISING_TIDE = 0xAFA3
ROOM_BUBBLE = 0xACB3
ROOM_BAT_CAVE = 0xB07A
ROOM_SPEED_HALL = 0xACF0
ROOM_SPEED = 0xAD1B
ROOM_SINGLE_CHAMBER = 0xAD5E
ROOM_DOUBLE_CHAMBER = 0xADAD
ROOM_WAVE = 0xADDE
ROOM_ICE_GATE = 0xA815
ROOM_ICE_ACID = 0xA75D  # Ice Beam Acid Room (tape entry path; not Tutorial)
ROOM_ICE_TUTORIAL = 0xA865
ROOM_ICE_SNAKE = 0xA8B9
ROOM_ICE = 0xA890

# K5/K6: Alpha PB return → Crateria Kihunter → Moat → West Ocean → WS → Phantoon
ROOM_RED_BRINSTAR_ELEVATOR = 0x962A
ROOM_CRATERIA_KIHUNTER = 0x948C
ROOM_MOAT = 0x95FF
ROOM_WEST_OCEAN = 0x93FE
ROOM_WS_ENTRANCE = 0xCA08  # Wrecked Ship Entrance (over-ocean spark)
ROOM_WS_MAIN = 0xCAF6  # Wrecked Ship Main Shaft
ROOM_WS_BASEMENT = 0xCC6F  # Wrecked Ship Basement (Gadora)
ROOM_PHANTOON = 0xCD13  # Phantoon's Room

__all__ = [
    "ROOM_CERES_ELEVATOR",
    "ROOM_CERES_FALLING",
    "ROOM_CERES_MAGNET",
    "ROOM_CERES_SCIENTIST",
    "ROOM_CERES_FLAT",
    "ROOM_CERES_RIDLEY",
    "ROOM_LANDING_SITE",
    "ROOM_PARLOR",
    "ROOM_CLIMB",
    "ROOM_PIT",
    "ROOM_BLUE_BRINSTAR_ELEVATOR",
    "ROOM_MORPH",
    "ROOM_CONSTRUCTION",
    "ROOM_BLUE_BRINSTAR_ETANK",
    "ROOM_FIRST_MISSILE",
    "ROOM_FLYWAY",
    "ROOM_BOMB_TORIZO",
    "ROOM_TERMINATOR",
    "ROOM_GREEN_PIRATES",
    "ROOM_LOWER_MUSHROOMS",
    "ROOM_GREEN_ELEVATOR",
    "ROOM_GREEN_MAIN_SHAFT",
    "ROOM_DACHORA",
    "ROOM_SPORE_KIHUNTER",
    "ROOM_SPORE_SPAWN",
    "ROOM_SUPER",
    "ROOM_FARMING",
    "ROOM_BIG_PINK",
    "ROOM_PINK_PB",
    "ROOM_GHZ",
    "ROOM_NOOB",
    "ROOM_RED_TOWER",
    "ROOM_HELLWAY",
    "ROOM_CATERPILLAR",
    "ROOM_ALPHA_PB",
    "ROOM_BAT",
    "ROOM_BELOW_SPAZER",
    "ROOM_SPAZER",
    "ROOM_WEST_TUNNEL",
    "ROOM_GLASS",
    "ROOM_EAST_TUNNEL",
    "ROOM_WAREHOUSE",
    "ROOM_BUSINESS",
    "ROOM_HJ_SHAFT",
    "ROOM_HJ",
    "ROOM_ZEELA",
    "ROOM_WAREHOUSE_KIHUNTER",
    "ROOM_BABY_KRAID",
    "ROOM_KRAID_EYE",
    "ROOM_KRAID",
    "ROOM_VARIA",
    "ROOM_FROG_SAVE",
    "ROOM_FROG_SPEEDWAY",
    "ROOM_UPPER_NORFAIR_FARM",
    "ROOM_CATHEDRAL_ENTRANCE",
    "ROOM_CATHEDRAL",
    "ROOM_RISING_TIDE",
    "ROOM_BUBBLE",
    "ROOM_BAT_CAVE",
    "ROOM_SPEED_HALL",
    "ROOM_SPEED",
    "ROOM_SINGLE_CHAMBER",
    "ROOM_DOUBLE_CHAMBER",
    "ROOM_WAVE",
    "ROOM_ICE_GATE",
    "ROOM_ICE_ACID",
    "ROOM_ICE_TUTORIAL",
    "ROOM_ICE_SNAKE",
    "ROOM_ICE",
    "ROOM_RED_BRINSTAR_ELEVATOR",
    "ROOM_CRATERIA_KIHUNTER",
    "ROOM_MOAT",
    "ROOM_WEST_OCEAN",
    "ROOM_WS_ENTRANCE",
    "ROOM_WS_MAIN",
    "ROOM_WS_BASEMENT",
    "ROOM_PHANTOON",
]
