"""Post-Supers ordered SpineHop table (product hop order).

DoorEdge meta on each hop is the continuous product source of truth.
Tip-level metadata lives in :mod:`super_metroid.routes.kpdr.tip_segments`.
Public facade: :mod:`super_metroid.routes.kpdr.spine`.
"""

from __future__ import annotations

from super_metroid.ram import HI_JUMP_MASK, VARIA_MASK
from super_metroid.routes.kpdr.pink_to_ghz import play_big_pink_to_ghz
from super_metroid.routes.kpdr.pink_shaft import play_big_pink_into_main_shaft
from super_metroid.routes.kpdr.to_bat_cave import play_bubble_to_bat_cave
from super_metroid.routes.kpdr.ghz_to_red import (
    play_ghz_to_noob,
    play_noob_to_red_tower,
)
from super_metroid.routes.kpdr.hijump import (
    play_business_to_hj_shaft,
    play_business_to_warehouse,
    play_hj_room_collect,
    play_hj_room_to_shaft,
    play_hj_shaft_to_business,
    play_hj_shaft_to_hj_room,
)
from super_metroid.routes.kpdr.k4_norfair import (
    play_business_to_cathedral_entrance,
    play_business_to_frog_save,
    play_cathedral_entrance_to_cathedral,
    play_cathedral_to_rising_tide,
    play_rising_tide_to_bubble,
)
from super_metroid.routes.kpdr.to_kraid import (
    play_baby_kraid_to_eye,
    play_eye_to_kraid,
    play_kihunter_to_baby_kraid,
    play_kraid_entry_to_varia,
    play_warehouse_to_zeela_with_hijump,
    play_zeela_to_kihunter,
)
from super_metroid.routes.kpdr.from_kraid import (
    play_baby_to_kihunter_return,
    play_eye_to_baby_return,
    play_kihunter_to_zeela_return,
    play_zeela_to_warehouse_return,
)
from super_metroid.routes.kpdr.red_stack import (
    play_bat_to_below_spazer,
    play_below_spazer_to_west,
    play_east_to_warehouse,
    play_glass_to_east,
    play_red_tower_to_bat,
    play_west_to_glass,
)
from super_metroid.routes.kpdr.rooms import (
    ROOM_BABY_KRAID,
    ROOM_BAT,
    ROOM_BAT_CAVE,
    ROOM_BELOW_SPAZER,
    ROOM_BIG_PINK,
    ROOM_BUBBLE,
    ROOM_BUSINESS,
    ROOM_CATHEDRAL,
    ROOM_CATHEDRAL_ENTRANCE,
    ROOM_EAST_TUNNEL,
    ROOM_FARMING,
    ROOM_FROG_SAVE,
    ROOM_GHZ,
    ROOM_GLASS,
    ROOM_HJ,
    ROOM_HJ_SHAFT,
    ROOM_KRAID,
    ROOM_KRAID_EYE,
    ROOM_NOOB,
    ROOM_RED_TOWER,
    ROOM_RISING_TIDE,
    ROOM_SUPER,
    ROOM_VARIA,
    ROOM_WAREHOUSE,
    ROOM_WAREHOUSE_KIHUNTER,
    ROOM_WEST_TUNNEL,
    ROOM_ZEELA,
)
from super_metroid.routes.kpdr.spine_types import (
    SpineHop,
    _BASE_CAPS,
    _HJ_CAPS,
    _K4_CAPS,
)
from super_metroid.routes.kpdr.super_collect import (
    play_farming_to_big_pink,
    play_super_room_to_farming,
)
from super_metroid.routes.kpdr.varia_return import (
    play_kraid_to_eye_return,
    play_varia_to_kraid,
)
from super_metroid.routes.kpdr.warehouse_stack import play_warehouse_to_business
from super_metroid.routes.runtime import RouteSession

__all__ = [
    "POST_SUPERS_SPINE",
]


def _require_big_pink_main_shaft(session: RouteSession) -> None:
    if session.state.room_id != ROOM_BIG_PINK or session.state.samus_x > 750:
        raise RuntimeError(
            f"Big Pink main shaft not reached: room=0x{session.state.room_id:04X} "
            f"x={session.state.samus_x}"
        )


def _require_hijump_collected(session: RouteSession) -> None:
    if not session.state.collected_items & HI_JUMP_MASK:
        raise RuntimeError(
            f"Hi-Jump not collected: items=0x{session.state.collected_items:04X}"
        )


def _require_varia_collected(session: RouteSession) -> None:
    if not session.state.collected_items & VARIA_MASK:
        raise RuntimeError(
            f"Varia not collected: items=0x{session.state.collected_items:04X}"
        )


# Ordered Super+ spine. Each hop is tagged with the tip segment it belongs to.
# Linear chain red_tower→…→business; frog and bat_cave branch from business.
POST_SUPERS_SPINE: tuple[SpineHop, ...] = (
    # --- red_tower (K1 after Super collect; Charge return intentionally omitted) ---
    SpineHop(
        "super_to_farming",
        play_super_room_to_farming,
        ROOM_SUPER,
        ROOM_FARMING,
        "farming",
        "red_tower",
        exit_direction="left",
        entry_direction="right",
        requires=frozenset({"super_missiles", "morph_ball", "bombs"}),
        policy_id="kpdr_super_room",
        edge_id="super_room_to_farming",
    ),
    SpineHop(
        "farming_to_big_pink",
        play_farming_to_big_pink,
        ROOM_FARMING,
        ROOM_BIG_PINK,
        "Big Pink",
        "red_tower",
        exit_direction="left",
        entry_direction="right",
        requires=frozenset({"super_missiles"}),
        policy_id="kpdr_super_room",
    ),
    SpineHop(
        "big_pink_main",
        play_big_pink_into_main_shaft,
        ROOM_BIG_PINK,
        ROOM_BIG_PINK,
        "Big Pink main shaft",
        "red_tower",
        use_transition_split=False,
        after=_require_big_pink_main_shaft,
        # in-room milestone — no DoorEdge
    ),
    SpineHop(
        "big_pink_to_ghz",
        play_big_pink_to_ghz,
        ROOM_BIG_PINK,
        ROOM_GHZ,
        "GHZ",
        "red_tower",
        exit_direction="right",
        entry_direction="left",
        requires=frozenset({"super_missiles", "morph_ball"}),
        policy_id="kpdr_big_pink",
    ),
    SpineHop(
        "ghz_to_noob",
        play_ghz_to_noob,
        ROOM_GHZ,
        ROOM_NOOB,
        "Noob",
        "red_tower",
        exit_direction="right",
        entry_direction="left",
        requires=frozenset({"morph_ball"}),
        policy_id="kpdr_green_hill",
    ),
    SpineHop(
        "noob_to_red_tower",
        play_noob_to_red_tower,
        ROOM_NOOB,
        ROOM_RED_TOWER,
        "Red Tower",
        "red_tower",
        exit_direction="right",
        entry_direction="left",
        requires=frozenset({"super_missiles"}),
        policy_id="kpdr_green_hill",
    ),
    # --- bat ---
    SpineHop(
        "red_tower_to_bat",
        play_red_tower_to_bat,
        ROOM_RED_TOWER,
        ROOM_BAT,
        "Bat Room",
        "bat",
        exit_direction="right",
        entry_direction="left",
        requires=frozenset({"morph_ball", "bombs", "super_missiles"}),
        policy_id="kpdr_red_tower",
    ),
    # --- below_spazer ---
    SpineHop(
        "bat_to_below_spazer",
        play_bat_to_below_spazer,
        ROOM_BAT,
        ROOM_BELOW_SPAZER,
        "Below Spazer",
        "below_spazer",
        exit_direction="right",
        entry_direction="left",
        requires=frozenset({"morph_ball", "bombs", "super_missiles"}),
        policy_id="kpdr_red_tower",
    ),
    # --- warehouse ---
    SpineHop(
        "below_spazer_to_west",
        play_below_spazer_to_west,
        ROOM_BELOW_SPAZER,
        ROOM_WEST_TUNNEL,
        "West Tunnel",
        "warehouse",
        exit_direction="right",
        entry_direction="left",
        requires=frozenset({"morph_ball", "bombs", "super_missiles"}),
        policy_id="kpdr_red_tower",
    ),
    SpineHop(
        "west_to_glass",
        play_west_to_glass,
        ROOM_WEST_TUNNEL,
        ROOM_GLASS,
        "Glass Tunnel",
        "warehouse",
        exit_direction="right",
        entry_direction="left",
        requires=frozenset({"morph_ball", "bombs", "super_missiles"}),
        policy_id="kpdr_red_tower",
    ),
    SpineHop(
        "glass_to_east",
        play_glass_to_east,
        ROOM_GLASS,
        ROOM_EAST_TUNNEL,
        "East Tunnel",
        "warehouse",
        exit_direction="right",
        entry_direction="left",
        requires=frozenset({"morph_ball", "bombs", "super_missiles"}),
        policy_id="kpdr_red_tower",
    ),
    SpineHop(
        "east_to_warehouse",
        play_east_to_warehouse,
        ROOM_EAST_TUNNEL,
        ROOM_WAREHOUSE,
        "Warehouse Entrance",
        "warehouse",
        exit_direction="right",
        entry_direction="left",
        requires=frozenset({"morph_ball", "bombs", "super_missiles"}),
        policy_id="kpdr_red_tower",
    ),
    # --- hijump (K2.7–K2.10) ---
    SpineHop(
        "warehouse_to_business",
        play_warehouse_to_business,
        ROOM_WAREHOUSE,
        ROOM_BUSINESS,
        "Business Center",
        "hijump",
        exit_direction="down",
        entry_direction="up",
        requires=_BASE_CAPS,
        policy_id="kpdr_hijump",
    ),
    SpineHop(
        "business_to_hj_shaft",
        play_business_to_hj_shaft,
        ROOM_BUSINESS,
        ROOM_HJ_SHAFT,
        "Hi-Jump shaft",
        "hijump",
        exit_direction="left",
        entry_direction="right",
        requires=_BASE_CAPS,
        policy_id="kpdr_hijump",
    ),
    SpineHop(
        "hj_shaft_to_hj_room",
        play_hj_shaft_to_hj_room,
        ROOM_HJ_SHAFT,
        ROOM_HJ,
        "Hi-Jump Room",
        "hijump",
        exit_direction="left",
        entry_direction="right",
        requires=_BASE_CAPS,
        policy_id="kpdr_hijump",
    ),
    SpineHop(
        "hijump_collected",
        play_hj_room_collect,
        ROOM_HJ,
        ROOM_HJ,
        "Hi-Jump collect",
        "hijump",
        use_transition_split=False,
        after=_require_hijump_collected,
        # in-room collect — no DoorEdge
    ),
    # --- kraid (K2.11–K2.18) ---
    SpineHop(
        "hj_room_to_shaft",
        play_hj_room_to_shaft,
        ROOM_HJ,
        ROOM_HJ_SHAFT,
        "Hi-Jump shaft return",
        "kraid",
        exit_direction="right",
        entry_direction="left",
        requires=_HJ_CAPS,
        policy_id="kpdr_hijump",
    ),
    SpineHop(
        "hj_shaft_to_business",
        play_hj_shaft_to_business,
        ROOM_HJ_SHAFT,
        ROOM_BUSINESS,
        "Business Center return",
        "kraid",
        exit_direction="right",
        entry_direction="left",
        requires=_HJ_CAPS,
        policy_id="kpdr_hijump",
    ),
    SpineHop(
        "business_to_warehouse",
        play_business_to_warehouse,
        ROOM_BUSINESS,
        ROOM_WAREHOUSE,
        "Warehouse return",
        "kraid",
        exit_direction="up",
        entry_direction="down",
        requires=_HJ_CAPS,
        policy_id="kpdr_hijump",
    ),
    SpineHop(
        "warehouse_to_zeela",
        play_warehouse_to_zeela_with_hijump,
        ROOM_WAREHOUSE,
        ROOM_ZEELA,
        "Warehouse Zeela",
        "kraid",
        exit_direction="right",
        entry_direction="left",
        requires=_HJ_CAPS,
        policy_id="kpdr_kraid_approach",
    ),
    SpineHop(
        "zeela_to_kihunter",
        play_zeela_to_kihunter,
        ROOM_ZEELA,
        ROOM_WAREHOUSE_KIHUNTER,
        "Warehouse Kihunter",
        "kraid",
        exit_direction="left",
        entry_direction="right",
        requires=_HJ_CAPS,
        policy_id="kpdr_kraid_approach",
    ),
    SpineHop(
        "kihunter_to_baby_kraid",
        play_kihunter_to_baby_kraid,
        ROOM_WAREHOUSE_KIHUNTER,
        ROOM_BABY_KRAID,
        "Baby Kraid",
        "kraid",
        exit_direction="right",
        entry_direction="left",
        requires=_HJ_CAPS,
        policy_id="kpdr_kraid_approach",
    ),
    SpineHop(
        "baby_kraid_to_eye",
        play_baby_kraid_to_eye,
        ROOM_BABY_KRAID,
        ROOM_KRAID_EYE,
        "Kraid Eye Door",
        "kraid",
        exit_direction="right",
        entry_direction="left",
        requires=_HJ_CAPS,
        policy_id="kpdr_kraid_approach",
    ),
    SpineHop(
        "eye_to_kraid",
        play_eye_to_kraid,
        ROOM_KRAID_EYE,
        ROOM_KRAID,
        "Kraid's Room",
        "kraid",
        exit_direction="right",
        entry_direction="left",
        requires=_HJ_CAPS,
        policy_id="kpdr_kraid_approach",
    ),
    # --- varia (K3) ---
    SpineHop(
        "kraid_to_varia",
        play_kraid_entry_to_varia,
        ROOM_KRAID,
        ROOM_VARIA,
        "Varia Suit Room",
        "varia",
        use_transition_split=False,
        after=_require_varia_collected,
        exit_direction="right",
        entry_direction="left",
        requires=_HJ_CAPS,
        policy_id="kpdr_kraid_combat",
    ),
    # --- business (K3 return) ---
    SpineHop(
        "varia_to_kraid_return",
        play_varia_to_kraid,
        ROOM_VARIA,
        ROOM_KRAID,
        "Kraid's Room return",
        "business",
        exit_direction="left",
        entry_direction="right",
        requires=_K4_CAPS,
        policy_id="kpdr_varia_return",
        edge_id="varia_to_kraid",
    ),
    SpineHop(
        "kraid_to_eye_return",
        play_kraid_to_eye_return,
        ROOM_KRAID,
        ROOM_KRAID_EYE,
        "Kraid Eye Door return",
        "business",
        exit_direction="left",
        entry_direction="right",
        requires=_K4_CAPS,
        policy_id="kpdr_varia_return",
    ),
    SpineHop(
        "eye_to_baby_return",
        play_eye_to_baby_return,
        ROOM_KRAID_EYE,
        ROOM_BABY_KRAID,
        "Baby Kraid return",
        "business",
        exit_direction="left",
        entry_direction="right",
        requires=_K4_CAPS,
        policy_id="kpdr_varia_return",
    ),
    SpineHop(
        "baby_to_kihunter_return",
        play_baby_to_kihunter_return,
        ROOM_BABY_KRAID,
        ROOM_WAREHOUSE_KIHUNTER,
        "Warehouse Kihunter return",
        "business",
        exit_direction="left",
        entry_direction="right",
        requires=_K4_CAPS,
        policy_id="kpdr_varia_return",
    ),
    SpineHop(
        "kihunter_to_zeela_return",
        play_kihunter_to_zeela_return,
        ROOM_WAREHOUSE_KIHUNTER,
        ROOM_ZEELA,
        "Warehouse Zeela return",
        "business",
        exit_direction="down",
        entry_direction="up",
        requires=_K4_CAPS,
        policy_id="kpdr_varia_return",
    ),
    SpineHop(
        "zeela_to_warehouse_return",
        play_zeela_to_warehouse_return,
        ROOM_ZEELA,
        ROOM_WAREHOUSE,
        "Warehouse Entrance return",
        "business",
        exit_direction="left",
        entry_direction="right",
        requires=_K4_CAPS,
        policy_id="kpdr_varia_return",
    ),
    SpineHop(
        "warehouse_to_business_return",
        play_warehouse_to_business,
        ROOM_WAREHOUSE,
        ROOM_BUSINESS,
        "Business Center return",
        "business",
        # Reuses continuous edge warehouse_to_business (hijump stage) — no new DoorEdge.
    ),
    # --- frog (K4.0; sibling of bat_cave under business) ---
    SpineHop(
        "business_to_frog_save",
        play_business_to_frog_save,
        ROOM_BUSINESS,
        ROOM_FROG_SAVE,
        "Frog Savestation",
        "frog",
        exit_direction="right",
        entry_direction="left",
        requires=_K4_CAPS,
        policy_id="kpdr_k4_speed",
    ),
    # --- bat_cave (K4.4 first Bubble; sibling of frog under business) ---
    SpineHop(
        "business_to_cathedral_entrance",
        play_business_to_cathedral_entrance,
        ROOM_BUSINESS,
        ROOM_CATHEDRAL_ENTRANCE,
        "Cathedral Entrance",
        "bat_cave",
        exit_direction="right",
        entry_direction="left",
        requires=_K4_CAPS,
        policy_id="kpdr_k4_cathedral",
    ),
    SpineHop(
        "cathedral_entrance_to_cathedral",
        play_cathedral_entrance_to_cathedral,
        ROOM_CATHEDRAL_ENTRANCE,
        ROOM_CATHEDRAL,
        "Cathedral",
        "bat_cave",
        exit_direction="right",
        entry_direction="left",
        requires=_K4_CAPS | frozenset({"super_missiles"}),
        policy_id="kpdr_k4_cathedral",
    ),
    SpineHop(
        "cathedral_to_rising_tide",
        play_cathedral_to_rising_tide,
        ROOM_CATHEDRAL,
        ROOM_RISING_TIDE,
        "Rising Tide",
        "bat_cave",
        exit_direction="right",
        entry_direction="left",
        requires=_K4_CAPS | frozenset({"super_missiles"}),
        policy_id="kpdr_k4_cathedral",
    ),
    SpineHop(
        "rising_tide_to_bubble",
        play_rising_tide_to_bubble,
        ROOM_RISING_TIDE,
        ROOM_BUBBLE,
        "Bubble Mountain",
        "bat_cave",
        exit_direction="right",
        entry_direction="left",
        requires=_K4_CAPS,
        policy_id="kpdr_k4_cathedral",
    ),
    SpineHop(
        "bubble_to_bat_cave",
        play_bubble_to_bat_cave,
        ROOM_BUBBLE,
        ROOM_BAT_CAVE,
        "Bat Cave",
        "bat_cave",
        exit_direction="right",
        entry_direction="left",
        requires=_K4_CAPS | frozenset({"super_missiles"}),
        policy_id="kpdr_k4_speed",
    ),
)
