"""Dungeon door-graph template for Zelda I (L2–L9 pathfinding primitive).

Public API re-exports (backward compatible with the former door_graph module).
"""

from __future__ import annotations

from zelda_i.door_graph.core import (
    DoorDir,
    GateKind,
    RoomExit,
    InventoryCaps,
    DungeonDoorGraph,
    door_dir_from_label,
    dirs_from_mask,
)
from zelda_i.door_graph.level2_exits import (
    LEVEL_2_DOOR_GRAPH,
    level_2_door_graph,
    L2_ENTRY,
    L2_ROPES,
    L2_WEST_KEY,
    L2_EAST_KEY,
    L2_EAST_OF_ROPES,
    L2_COMPASS,
    L2_BOMB_N,
    L2_GORIYA_WEST,
    L2_ROPES_NORTH,
    L2_BOOM,
    L2_TRAPS_KEESE,
    L2_MOLDORM,
    L2_ROPES_UNLOCK,
    L2_GORIYA_BOMBS,
    L2_DODONGO,
    L2_WEST_OF_BOSS,
    L2_OW_DOOR_SCREEN,
)
from zelda_i.door_graph.level3_exits import (
    LEVEL_3_DOOR_GRAPH,
    level_3_door_graph,
    L3_ENTRY,
    L3_WEST_KEY,
    L3_NORTH_ZOLS,
    L3_DARKNUTS,
    L3_ZOL_KEY_4B,
    L3_COMPASS,
    L3_WEST_DARKNUTS,
    L3_SOUTH_DARKNUTS,
    L3_RAFT_PASSAGE,
    L3_MAP_4C,
    L3_BOMB_SHORTCUT,
    L3_KEESE_4A,
)

__all__ = [
    "DoorDir",
    "GateKind",
    "RoomExit",
    "InventoryCaps",
    "DungeonDoorGraph",
    "LEVEL_2_DOOR_GRAPH",
    "level_2_door_graph",
    "LEVEL_3_DOOR_GRAPH",
    "level_3_door_graph",
    "door_dir_from_label",
    "dirs_from_mask",
    "L2_ENTRY",
    "L2_ROPES",
    "L2_WEST_KEY",
    "L2_EAST_KEY",
    "L2_EAST_OF_ROPES",
    "L2_COMPASS",
    "L2_BOMB_N",
    "L2_GORIYA_WEST",
    "L2_ROPES_NORTH",
    "L2_BOOM",
    "L2_TRAPS_KEESE",
    "L2_MOLDORM",
    "L2_ROPES_UNLOCK",
    "L2_GORIYA_BOMBS",
    "L2_DODONGO",
    "L2_WEST_OF_BOSS",
    "L2_OW_DOOR_SCREEN",
    "L3_ENTRY",
    "L3_WEST_KEY",
    "L3_NORTH_ZOLS",
    "L3_DARKNUTS",
    "L3_ZOL_KEY_4B",
    "L3_COMPASS",
    "L3_WEST_DARKNUTS",
    "L3_SOUTH_DARKNUTS",
    "L3_RAFT_PASSAGE",
    "L3_MAP_4C",
    "L3_BOMB_SHORTCUT",
    "L3_KEESE_4A",
]
