"""Repeatable FCEUX 2.6.6 checkpoint extractor for HappyLee #1715M.

Runs the original FM2 under installed FCEUX (not BizHawk / not fceumm) and
writes RAM-rich named checkpoints + a dense mid-level trace.

```bash
# Full oracle dump (Xvfb + FCEUX movie play + Lua RAM dump)
SDL_VIDEODRIVER=dummy \\
  uv run python -m smb.tas.oracle.extract_fceux_checkpoints

# Re-parse existing dumps only
uv run python -m smb.tas.oracle.extract_fceux_checkpoints --no-run
```

Outputs (stable, timestamp-free names under ``oracle_happylee_8_3/``)::

    fceux_ram_trace.jsonl
    fceux_named_checkpoints.jsonl
    fceux_checkpoints.json
    extract_evidence.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

from smb.paths import GAME_DIR, RECORDINGS_DIR, REPO_ROOT
from smb.tas.stages import DEFAULT_FM2 as STAGE_DEFAULT_FM2

ORACLE_DIR = GAME_DIR / "tas" / "oracle"
ORACLE_EVIDENCE_DIR = RECORDINGS_DIR / "tas_import" / "oracle_happylee_8_3"
DEFAULT_FM2 = STAGE_DEFAULT_FM2
DEFAULT_ROM = GAME_DIR / "roms" / "Super Mario Bros..nes"
LUA_SCRIPT = ORACLE_DIR / "dump_ram_trace.lua"
RUN_CFG = ORACLE_DIR / "_run_config.lua"
RUN_ENTRY = ORACLE_DIR / "_run_entry.lua"

# Dense window covers 8-2 leave through 8-4 control on the oracle movie.
DEFAULT_START = 10800
DEFAULT_END = 15500
DEFAULT_DENSE_FROM = 12800
DEFAULT_DENSE_TO = 15250


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _sha1(path: Path) -> str:
    h = hashlib.sha1()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest().upper()


def _rom_body_sha1(path: Path) -> str:
    data = path.read_bytes()
    body = data[16:] if data[:4] == b"NES\x1a" else data
    return hashlib.sha1(body).hexdigest().upper()


def _fceux_version() -> str:
    try:
        proc = subprocess.run(
            ["fceux", "--help"],
            capture_output=True,
            text=True,
            timeout=15,
            check=False,
        )
        # stderr/stdout both may carry the banner
        blob = (proc.stdout or "") + "\n" + (proc.stderr or "")
        for line in blob.splitlines():
            if "FCEUX" in line and any(c.isdigit() for c in line):
                return line.strip()
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        return f"unavailable: {exc}"
    return "FCEUX (version banner not parsed)"


def write_run_config(
    *,
    out_trace: Path,
    out_named: Path,
    start_frame: int = DEFAULT_START,
    end_frame: int = DEFAULT_END,
    dense_from: int = DEFAULT_DENSE_FROM,
    dense_to: int = DEFAULT_DENSE_TO,
    sample_every: int = 1,
) -> Path:
    """Write Lua cfg with **absolute** output paths next to dump_ram_trace.lua.

    FCEUX CWD is unreliable (xvfb-run, Qt startup, movie dir). The Lua
    script loads this file via ``debug.getinfo`` script-dir (not CWD) and
    requires absolute ``out_*`` paths so dumps never land relative to CWD.
    """
    ORACLE_DIR.mkdir(parents=True, exist_ok=True)
    out_trace = out_trace.resolve()
    out_named = out_named.resolve()
    out_trace.parent.mkdir(parents=True, exist_ok=True)
    out_named.parent.mkdir(parents=True, exist_ok=True)

    text = (
        "-- AUTO-GENERATED by extract_fceux_checkpoints.py — absolute paths only\n"
        "return {\n"
        f'  out_trace = "{out_trace}",\n'
        f'  out_named = "{out_named}",\n'
        f"  start_frame = {int(start_frame)},\n"
        f"  end_frame = {int(end_frame)},\n"
        f"  dense_from = {int(dense_from)},\n"
        f"  dense_to = {int(dense_to)},\n"
        f"  sample_every = {int(sample_every)},\n"
        "}\n"
    )
    RUN_CFG.write_text(text, encoding="utf-8")
    # Optional entry for debugging; not used by run_fceux_dump (dofile hangs
    # the FCEUX lua thread — load dump_ram_trace.lua directly instead).
    entry = (
        "-- AUTO-GENERATED (debug only; prefer --loadlua dump_ram_trace.lua)\n"
        f'SMB_ORACLE_CFG_PATH = "{RUN_CFG.resolve()}"\n'
        f'-- dofile("{LUA_SCRIPT.resolve()}")  -- DO NOT: dofile breaks frame loop\n'
    )
    RUN_ENTRY.write_text(entry, encoding="utf-8")
    return RUN_CFG


def run_fceux_dump(
    *,
    fm2: Path = DEFAULT_FM2,
    rom: Path = DEFAULT_ROM,
    out_trace: Path | None = None,
    out_named: Path | None = None,
    start_frame: int = DEFAULT_START,
    end_frame: int = DEFAULT_END,
    dense_from: int = DEFAULT_DENSE_FROM,
    dense_to: int = DEFAULT_DENSE_TO,
    timeout_s: float = 600.0,
) -> dict[str, Any]:
    """Play FM2 under FCEUX with the RAM-dump Lua script.

    Prefers ``xvfb-run`` when DISPLAY is unset or dummy.
    """
    out_trace = (out_trace or (ORACLE_EVIDENCE_DIR / "fceux_ram_trace.jsonl")).resolve()
    out_named = (out_named or (ORACLE_EVIDENCE_DIR / "fceux_named_checkpoints.jsonl")).resolve()
    fm2 = fm2.resolve()
    rom = rom.resolve()
    ORACLE_EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)

    if not fm2.is_file():
        raise FileNotFoundError(f"FM2 not found: {fm2}")
    if not rom.is_file():
        raise FileNotFoundError(f"ROM not found: {rom}")
    if not LUA_SCRIPT.is_file():
        raise FileNotFoundError(f"Lua script not found: {LUA_SCRIPT}")

    write_run_config(
        out_trace=out_trace,
        out_named=out_named,
        start_frame=start_frame,
        end_frame=end_frame,
        dense_from=dense_from,
        dense_to=dense_to,
    )

    # Wipe previous dumps so partial runs cannot mix.
    for p in (out_trace, out_named):
        if p.exists():
            p.unlink()

    # All FCEUX file args absolute; load dump script directly (not a dofile
    # wrapper — FCEUX's lua thread does not keep frame loops alive under dofile).
    # cwd fixed to REPO_ROOT for determinism even though out paths are absolute.
    lua_abs = str(LUA_SCRIPT.resolve())
    fceux_cmd = [
        "fceux",
        "--no-config",
        "1",
        "--sound",
        "0",
        "--playmov",
        str(fm2),
        "--loadlua",
        lua_abs,
        str(rom),
    ]
    # Headless: always prefer Xvfb for stability on shared agents.
    # Wrap with timeout(1) so a stuck Qt exit still yields control after dumps.
    timeout_bin = shutil.which("timeout")
    inner = fceux_cmd
    if shutil.which("xvfb-run"):
        inner = ["xvfb-run", "-a", "-s", "-screen 0 640x480x24"] + fceux_cmd
    if timeout_bin:
        # TERM then KILL; budget matches timeout_s.
        cmd = [
            timeout_bin,
            f"--kill-after=10",
            str(max(30, int(timeout_s))),
        ] + inner
    else:
        cmd = inner

    env = os.environ.copy()
    env.setdefault("SDL_VIDEODRIVER", "dummy")
    env.setdefault("SDL_AUDIODRIVER", "dummy")

    t0 = time.time()
    proc = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        timeout=timeout_s + 30.0,
        check=False,
        cwd=str(REPO_ROOT.resolve()),
        env=env,
    )
    elapsed = time.time() - t0
    return {
        "cmd": cmd,
        "cwd": str(REPO_ROOT.resolve()),
        "returncode": proc.returncode,
        "elapsed_s": round(elapsed, 3),
        "stdout_tail": (proc.stdout or "")[-2000:],
        "stderr_tail": (proc.stderr or "")[-2000:],
        "out_trace": str(out_trace),
        "out_named": str(out_named),
        "cfg_path": str(RUN_CFG.resolve()),
        "lua_path": lua_abs,
        "trace_exists": out_trace.is_file(),
        "named_exists": out_named.is_file(),
        "trace_bytes": out_trace.stat().st_size if out_trace.is_file() else 0,
        "named_bytes": out_named.stat().st_size if out_named.is_file() else 0,
    }


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    if not path.is_file():
        return rows
    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def build_checkpoint_table(named_rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Normalize named checkpoint rows into a stable table (skip _summary)."""
    table: list[dict[str, Any]] = []
    for row in named_rows:
        name = row.get("name")
        if not name or str(name).startswith("_"):
            continue
        table.append(
            {
                "name": name,
                "movie_frame": row.get("movie_frame"),
                "world": row.get("world"),
                "level": row.get("level"),
                "area_pointer": row.get("area_pointer"),
                "oper_mode": row.get("oper_mode"),
                "player_state": row.get("player_state"),
                "player_x": row.get("player_x"),
                "player_y": row.get("player_y"),
                "x_frac": row.get("x_frac"),
                "y_frac": row.get("y_frac"),
                "x_speed": row.get("x_speed"),
                "y_speed": row.get("y_speed"),
                "grounded": row.get("grounded"),
                "timer": row.get("timer"),
                "timer_mod21": row.get("timer_mod21"),
                "lives": row.get("lives"),
                "screen_x": row.get("screen_x"),
                "frame_counter": row.get("frame_counter"),
                "enemies": row.get("enemies") or [],
                "snapshot": row,
            }
        )
    return table


def extract_checkpoints(
    *,
    run: bool = True,
    fm2: Path = DEFAULT_FM2,
    rom: Path = DEFAULT_ROM,
    end_frame: int = DEFAULT_END,
) -> dict[str, Any]:
    """Run FCEUX dump (optional) and assemble evidence JSON."""
    ORACLE_EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
    out_trace = ORACLE_EVIDENCE_DIR / "fceux_ram_trace.jsonl"
    out_named = ORACLE_EVIDENCE_DIR / "fceux_named_checkpoints.jsonl"
    out_table = ORACLE_EVIDENCE_DIR / "fceux_checkpoints.json"
    out_evidence = ORACLE_EVIDENCE_DIR / "extract_evidence.json"

    run_info: dict[str, Any] | None = None
    if run:
        # Extend end_frame if we want ending confirmation (user: 18000 for thank-you).
        run_info = run_fceux_dump(
            fm2=fm2,
            rom=rom,
            out_trace=out_trace,
            out_named=out_named,
            end_frame=end_frame,
        )

    named = load_jsonl(out_named)
    trace = load_jsonl(out_trace)
    table = build_checkpoint_table(named)

    # Index key named frames for quick lookup
    by_name = {r["name"]: r for r in table}

    payload = {
        "schema": "smb.fceux_oracle_checkpoints.v1",
        "oracle": "FCEUX 2.6.6 + HappyLee #1715M FM2 (not BizHawk, not fceumm)",
        "fceux_version": _fceux_version(),
        "fm2_path": str(fm2),
        "fm2_sha256": _sha256(fm2) if fm2.is_file() else None,
        "rom_path": str(rom),
        "rom_sha1_full": _sha1(rom) if rom.is_file() else None,
        "rom_sha1_body": _rom_body_sha1(rom) if rom.is_file() else None,
        "rom_sha1_body_expected": "FACEE9C577A5262DBE33AC4930BB0B58C8C037F7",
        "checkpoints": table,
        "checkpoint_names": [r["name"] for r in table],
        "key_frames": {
            k: by_name[k]["movie_frame"]
            for k in (
                "control_8_2",
                "leave_8_2_to_8_3",
                "control_8_3",
                "early_8_3_after_first_obstacle",
                "mid_8_3_x900",
                "mid_8_3_x1600",
                "hammer_bro_nearby_8_3",
                "flag_approach_8_3",
                "flagpole_grab_8_3",
                "leave_8_3_to_8_4",
                "control_8_4",
                "ending_oper_mode_2",
            )
            if k in by_name
        },
        "trace_frames": len(trace),
        "named_rows": len(named),
    }
    out_table.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    evidence = {
        **payload,
        "run": run_info,
        "outputs": {
            "trace": str(out_trace),
            "named": str(out_named),
            "checkpoints": str(out_table),
        },
        "repro_cmd": (
            "uv run python -m smb.tas.oracle.extract_fceux_checkpoints"
        ),
    }
    # Drop bulky nested snapshots from evidence top-level for readability;
    # keep names + frames + first-class fields.
    slim_cps = []
    for r in table:
        slim = {k: v for k, v in r.items() if k != "snapshot"}
        slim_cps.append(slim)
    evidence["checkpoints"] = slim_cps
    out_evidence.write_text(json.dumps(evidence, indent=2) + "\n", encoding="utf-8")
    return evidence


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--no-run", action="store_true", help="Only re-parse existing dumps")
    ap.add_argument("--fm2", type=Path, default=DEFAULT_FM2)
    ap.add_argument("--rom", type=Path, default=DEFAULT_ROM)
    ap.add_argument(
        "--end-frame",
        type=int,
        default=DEFAULT_END,
        help="Stop dump at this movie frame (default covers 8-4 control)",
    )
    ap.add_argument(
        "--to-ending",
        action="store_true",
        help="Extend dump to frame 18100 (thank-you region)",
    )
    args = ap.parse_args(argv)
    end = 18100 if args.to_ending else args.end_frame
    # Stable CWD (absolute Lua paths still make this non-critical).
    os.chdir(REPO_ROOT.resolve())
    evidence = extract_checkpoints(
        run=not args.no_run,
        fm2=args.fm2,
        rom=args.rom,
        end_frame=end,
    )
    print(json.dumps(
        {
            "ok": bool(evidence.get("key_frames")),
            "key_frames": evidence.get("key_frames"),
            "checkpoint_names": evidence.get("checkpoint_names"),
            "trace_frames": evidence.get("trace_frames"),
            "fceux_version": evidence.get("fceux_version"),
            "fm2_sha256": evidence.get("fm2_sha256"),
            "rom_sha1_body": evidence.get("rom_sha1_body"),
            "outputs": evidence.get("outputs"),
            "run_returncode": (evidence.get("run") or {}).get("returncode"),
        },
        indent=2,
    ))
    if not evidence.get("key_frames"):
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
