-- K5 reverse-tunnel geometry — room-prefixed constants only.

local M = {}

M.WH_EAST_DOOR_X = 28
M.WH_ELEV_BAND_X_MAX = 60
M.WH_ELEV_BAND_Y_MAX = 160
M.WH_TO_EAST_FRAMES = 900
M.WH_TO_EAST_SETTLE = 360

M.EAST_RETURN_X_MAX = 280
M.EAST_RETURN_Y_MIN = 100
M.EAST_RETURN_Y_MAX = 450
M.EAST_GLASS_DOOR_X = 40
M.EAST_TO_GLASS_FRAMES = 600
M.EAST_TO_GLASS_SETTLE = 260

M.GLASS_WEST_DOOR_X = 40
M.GLASS_TO_WEST_RUN = 80
M.GLASS_TO_WEST_SHOOT = 5
M.GLASS_TO_WEST_SPIN = 50
M.GLASS_TO_WEST_HOLD = 300
M.GLASS_TO_WEST_SETTLE = 260

M.WEST_BELOW_DOOR_X = 40
M.WEST_TO_BELOW_RUN = 80
M.WEST_TO_BELOW_SHOOT = 5
M.WEST_TO_BELOW_SPIN = 50
M.WEST_TO_BELOW_HOLD = 300
M.WEST_TO_BELOW_SETTLE = 260

M.BELOW_BAT_DOOR_X = 40
M.BELOW_TO_BAT_FRAMES = 2000
M.BELOW_TO_BAT_SETTLE = 260
M.BAT_SILL_X_MIN = 400
M.BAT_SILL_X_MAX = 500
M.BAT_SILL_Y_MIN = 100
M.BAT_SILL_Y_MAX = 165
M.BAT_SILL_PIN_FRAMES = 240

M.BAT_TO_RED_DOOR_SEAT_X = 80
M.BAT_TO_RED_HIGH_Y = 165
M.BAT_TO_RED_TRAVERSE_BUDGET = 2200
M.BAT_TO_RED_PROGRESS_WINDOW = 42
M.BAT_TO_RED_JUMP_PERIOD = 36
M.BAT_TO_RED_JUMP_HOLD = 24
M.BAT_TO_RED_RUNUP = 20
M.BAT_TO_RED_WATER_CJ_CROUCH = 4
M.BAT_TO_RED_WATER_CJ_JUMP = 16
M.BAT_TO_RED_WATER_GRAB = 24
M.BAT_TO_RED_EXIT_RUN = 20
M.BAT_TO_RED_EXIT_SHOOT = 4
M.BAT_TO_RED_EXIT_SPIN = 30
M.BAT_TO_RED_EXIT_HOLD = 280
M.BAT_TO_RED_EXIT_SETTLE = 360

M.RED_BOTTOM_Y = 2440
M.RED_LOWER_LIP_Y = 2090
M.RED_TUNNEL_Y = 1880
M.RED_FLOOR_Y = 1600
M.RED_TOP_DOOR_Y = 180
M.RED_TOP_DOOR_X = 220
M.RED_ZIG_X_MIN = 45
M.RED_ZIG_X_MAX = 220
M.RED_CLIMB_FRAMES = 9000
M.RED_TO_HELLWAY_EXIT_RUN = 24
M.RED_TO_HELLWAY_EXIT_SHOOT = 4
M.RED_TO_HELLWAY_EXIT_SPIN = 36
M.RED_TO_HELLWAY_EXIT_HOLD = 320
M.RED_TO_HELLWAY_EXIT_SETTLE = 360

return M
