"""Reusable Super Metroid route skills (geometry, walljump, runway, door, knockback).

Skills take :class:`~super_metroid.routes.runtime.ControllerSession` plus a
**policy** object (or explicit kwargs). Room geometry lives in
:mod:`super_metroid.routes.skills.policies`, not in skill bodies.

Product hops compose skills — e.g. :mod:`super_metroid.routes.kpdr.to_bat_cave`.
"""

from __future__ import annotations

from super_metroid.routes.controller_common import (
    POSE_WALL_LATCH,
    WallJumpTiming,
    is_wall_latch,
)
from super_metroid.routes.skills.door import (
    super_door_pressure_frame,
    top_super_door,
)
from super_metroid.routes.skills.door_exit import (
    JUMP_ENTER_PERIOD,
    beam_open_door,
    drain_door_transition,
    jump_enter_exit,
    lip_stage,
    period_exit_push,
)
from super_metroid.routes.skills.morph_bomb import (
    align_x,
    morph_bomb_hole_climb,
    morph_roll_to_window,
    morph_upper_plant,
)
from super_metroid.routes.skills.geometry import (
    TRUE_GROUND,
    STAND_PIN,
    STANDING_POSES,
    POSE_KNOCKBACK,
    POSE_STAND_LEFT,
    POSE_STAND_RIGHT,
    BubblePhaseStop,
    BubbleTrack,
    ClimbTrack,
    PhaseStop,
    avoid_wrong_door,
    in_xy_band,
    is_stand_pin_pose,
    is_true_ground,
    new_climb_track,
    on_launch_lip,
    on_mid_iso_pin,
    on_right_shelf,
    on_save_runway,
    phase_c_usable_right_contact,
    phase_d_near_top,
    phase_d_top_band,
    track_state,
)
from super_metroid.routes.skills.knockback import (
    escape_knockback_spin,
    hold_through_knockback,
    is_knockback,
)
from super_metroid.routes.skills.runway import (
    BubbleEnemySnap,
    EnemySnap,
    fire_phase_clear,
    fire_phase_geometry,
    prepare_fire_run,
    read_enemy_slot,
    runway_dash,
    save_runway_fire_recipe,
    save_runway_open_loop,
    seat_max_left_fire,
    spin_glide,
    stationary_missile_clear,
    wait_fire_phase,
    walk_brake_to_x,
)
from super_metroid.routes.skills.walljump import (
    consecutive_walljumps,
    damage_boost_hold,
    double_walljump,
    period_walljump_climb,
    wait_wall_latch,
    wait_wall_ready,
    wall_approach_band,
    walljump_approach_coast,
    walljump_once,
    walljump_second_left_wall,
)
from super_metroid.routes.skills.shinespark import (
    ECHOES_FULL,
    SPARK_POSES,
    TYPICAL_ARM_TIMER,
    activate_shinespark,
    charge_store_activate,
    charge_until_boost,
    crouch_store,
    read_spark_wram,
    store_then_spin_unspin_activate,
    wait_store_window,
)

# Historical bubble_* skill names (stable for tests / scripts mid-migration).
from super_metroid.routes.skills.door import bubble_top_super_door
from super_metroid.routes.skills.runway import (
    bubble_fire_phase_clear,
    bubble_fire_phase_geometry,
    bubble_prepare_fire_run,
    bubble_read_enemy_slot,
    bubble_runway_dash,
    bubble_save_runway_fire_recipe,
    bubble_save_runway_open_loop_r15,
    bubble_seat_max_left_fire,
    bubble_spin_glide,
    bubble_stationary_missile_clear,
    bubble_wait_fire_phase,
    bubble_walk_brake_to_x,
)
from super_metroid.routes.skills.walljump import (
    bubble_consecutive_walljumps,
    bubble_damage_boost_hold,
    bubble_double_walljump_r15,
    bubble_is_knockback,
    bubble_is_wall_latch,
    bubble_period_walljump_climb,
    bubble_wait_wall_latch,
    bubble_wait_wall_ready,
    bubble_wall_approach_band,
    bubble_walljump_approach_coast,
    bubble_walljump_once,
    bubble_walljump_second_left_wall,
)

# Policy timings re-exported for skill-library tests.
from super_metroid.routes.skills.policies.bubble_to_bat import (
    DAMAGE_BOOST_HX,
    HIJUMP_WALLJUMP_VY0,
    REGULAR_WALLJUMP_VY0,
    R15_DOUBLE,
    R15_WJ1,
    R15_WJ2,
)

__all__ = [
    "POSE_WALL_LATCH",
    "WallJumpTiming",
    "is_wall_latch",
    "TRUE_GROUND",
    "STAND_PIN",
    "STANDING_POSES",
    "POSE_KNOCKBACK",
    "POSE_STAND_LEFT",
    "POSE_STAND_RIGHT",
    "BubblePhaseStop",
    "BubbleTrack",
    "ClimbTrack",
    "PhaseStop",
    "avoid_wrong_door",
    "in_xy_band",
    "is_stand_pin_pose",
    "is_true_ground",
    "new_climb_track",
    "on_launch_lip",
    "on_mid_iso_pin",
    "on_right_shelf",
    "on_save_runway",
    "phase_c_usable_right_contact",
    "phase_d_near_top",
    "phase_d_top_band",
    "track_state",
    "EnemySnap",
    "BubbleEnemySnap",
    "stationary_missile_clear",
    "walk_brake_to_x",
    "seat_max_left_fire",
    "prepare_fire_run",
    "runway_dash",
    "spin_glide",
    "read_enemy_slot",
    "fire_phase_geometry",
    "fire_phase_clear",
    "wait_fire_phase",
    "save_runway_fire_recipe",
    "save_runway_open_loop",
    "is_knockback",
    "hold_through_knockback",
    "escape_knockback_spin",
    "wall_approach_band",
    "wait_wall_ready",
    "wait_wall_latch",
    "walljump_approach_coast",
    "walljump_once",
    "consecutive_walljumps",
    "double_walljump",
    "walljump_second_left_wall",
    "period_walljump_climb",
    "damage_boost_hold",
    "super_door_pressure_frame",
    "top_super_door",
    "JUMP_ENTER_PERIOD",
    "beam_open_door",
    "drain_door_transition",
    "jump_enter_exit",
    "lip_stage",
    "period_exit_push",
    "align_x",
    "morph_bomb_hole_climb",
    "morph_roll_to_window",
    "morph_upper_plant",
    "ECHOES_FULL",
    "SPARK_POSES",
    "TYPICAL_ARM_TIMER",
    "read_spark_wram",
    "charge_until_boost",
    "crouch_store",
    "wait_store_window",
    "activate_shinespark",
    "store_then_spin_unspin_activate",
    "charge_store_activate",
    "HIJUMP_WALLJUMP_VY0",
    "REGULAR_WALLJUMP_VY0",
    "DAMAGE_BOOST_HX",
    "R15_DOUBLE",
    "R15_WJ1",
    "R15_WJ2",
    # bubble_* aliases
    "bubble_top_super_door",
    "bubble_stationary_missile_clear",
    "bubble_walk_brake_to_x",
    "bubble_seat_max_left_fire",
    "bubble_prepare_fire_run",
    "bubble_runway_dash",
    "bubble_spin_glide",
    "bubble_read_enemy_slot",
    "bubble_fire_phase_geometry",
    "bubble_fire_phase_clear",
    "bubble_wait_fire_phase",
    "bubble_save_runway_fire_recipe",
    "bubble_save_runway_open_loop_r15",
    "bubble_is_wall_latch",
    "bubble_is_knockback",
    "bubble_wall_approach_band",
    "bubble_wait_wall_ready",
    "bubble_wait_wall_latch",
    "bubble_walljump_approach_coast",
    "bubble_walljump_once",
    "bubble_consecutive_walljumps",
    "bubble_double_walljump_r15",
    "bubble_walljump_second_left_wall",
    "bubble_period_walljump_climb",
    "bubble_damage_boost_hold",
]
