#!/usr/bin/env python3
"""Scaffold one pure-first continuous tip extension (recipe steps 1–5 checklist).

Does **not** claim continuous green or edit STATUS. Generates:

1. Pure controller stub in ``routes/kpdr/<module>.py`` (optional append)
2. Registry registration snippet / optional write
3. Residual skeleton under ``docs/tasks/``
4. Printed checklist for graph edge, catalog tip, SpineHop/TipSpec, run_to wire

Usage (from repo root)::

  uv run python snes/super_metroid/scripts/scaffold_tip.py \\
    --segment business_to_frog_save \\
    --from-room 0xA7DE --to-room 0xB167 \\
    --module k4_norfair --card-id SM-K4-BUBBLE-01 --dry-run

  uv run python snes/super_metroid/scripts/scaffold_tip.py \\
    --segment my_hop --from-room 0xA7DE --to-room 0xB167 \\
    --module k4_norfair --card-id SM-K4-XX --write
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
_SNES_IMPORT_ROOT = Path(__file__).resolve().parents[2]
for _p in (ROOT, globals().get('_SNES_IMPORT_ROOT', ROOT)):
    if _p is not None and str(_p) not in sys.path:
        sys.path.insert(0, str(_p))
SM = ROOT / "snes" / "super_metroid"
KPDR = SM / "routes" / "kpdr"
TASKS = SM / "docs" / "tasks"
REGISTRY = KPDR / "registry.py"


def _snake(s: str) -> str:
    s = s.strip().replace("-", "_")
    s = re.sub(r"[^a-zA-Z0-9_]+", "_", s)
    return s.lower().strip("_")


def _fn_name(segment: str) -> str:
    return f"play_{_snake(segment)}"


def _controller_stub(
    *,
    segment: str,
    from_room: int,
    to_room: int,
    module: str,
) -> str:
    fn = _fn_name(segment)
    label = _snake(segment)
    return f'''

def {fn}(session: ControllerSession) -> SuperMetroidState:
    """Scaffold {_snake(segment)}: 0x{from_room:04X} → 0x{to_room:04X}.

    Pure-first: green from continuous-like source before continuous tip wire.
    Generated by scripts/scaffold_tip.py — replace geometry before claiming green.
    """
    require_room(session, 0x{from_room:04X}, "{label}")
    # TODO: replace scaffold with real geometry (one knob at a time).
    for _ in range(240):
        state = hold(session, 1, reason="{label}_scaffold")
        if state.room_id == 0x{to_room:04X}:
            return state
    state = session.state
    raise TimeoutError(
        f"{label}: scaffold timeout before room 0x{to_room:04X}; "
        f"room=0x{{state.room_id:04X}} pose={{state.pose}} "
        f"xy=({{state.samus_x}},{{state.samus_y}})"
    )
'''


def _ensure_module_header(path: Path) -> str:
    if path.is_file():
        return path.read_text(encoding="utf-8")
    return f'''"""KPDR controllers for tip extension (scaffold).

Generated / extended via ``scripts/scaffold_tip.py``.
"""

from __future__ import annotations

from super_metroid.ram import SuperMetroidState
from super_metroid.routes.controller_common import hold, require_room
from super_metroid.routes.runtime import ControllerSession
'''


def _residual_md(
    *,
    card_id: str,
    segment: str,
    from_room: int,
    to_room: int,
    module: str,
) -> str:
    fn = _fn_name(segment)
    return f"""# TASK {card_id}: pure scaffold `{segment}`

## Recipe step
1 pure controller

## Model
Luna

## Wave type
implement

## Own files only
- routes/kpdr/{module}.py
- routes/kpdr/registry.py
- docs/tasks/{card_id}-residual.md

## Context (minimal)
- Continuous tip verified: power-on → Varia (`--to varia`, 101,954f)
- Process: docs/tasks/PROCESS.md
- Scaffold generated by scripts/scaffold_tip.py — geometry still TODO

## Read first
- docs/tasks/PROCESS.md
- docs/SOURCE_STATES.md
- routes/kpdr/varia_return.py  # style reference

## Do
1. Pure-green `{fn}` from continuous-like source (room 0x{from_room:04X}).
2. One-knob geometry only; leave residual with next card ID.
3. Do not wire continuous.py / STATUS.

## Do not
- Touch continuous.py / STATUS.md
- Claim continuous green from scaffold
- Full-bank WRAM in hot loops

## Acceptance
- [ ] `uv run pytest super_metroid/tests/test_controller_common.py -q` (or segment unit)
- [ ] pure probe green from listed source (when geometry ready)
- [ ] Residual uses PROCESS schema

## Verify commands
```bash
uv run python snes/super_metroid/scripts/probe/kpdr.py suggest-source --room 0x{from_room:04X} --segment {segment}
# After geometry lands:
# uv run python snes/super_metroid/scripts/probe/kpdr.py pure <seg> --source <state> --pin-json snes/super_metroid/debug/{segment}_pin.json
```

## Done when
Residual below. Integrity / STATUS stays with planner.

---

## Residual — {card_id}

### Result
PARTIAL

### Files changed
- routes/kpdr/{module}.py — scaffold `{fn}` 0x{from_room:04X}→0x{to_room:04X}

### Verify paste
(scaffold only — pure not green)

### Acceptance
- [ ] pure green (pending geometry)

### Residual risks
- Scaffold timeout placeholder; no real door geometry yet.

### Next action (required)
- **Next card ID:** {card_id}B
- **One change:** replace scaffold hold loop with first geometry knob for 0x{from_room:04X}→0x{to_room:04X}
- **Source state:** needs capture or catalog match for room 0x{from_room:04X}

### Non-claims
- Did not STATUS-promote
- Did not forge progression/capacity/door/event/boss RAM
- Not continuous evidence

### Probe pin (if pure/geometry)
room=0x{from_room:04X} pose=… x=… y=… door_transition=… frames=…
"""


def _checklist(
    *,
    segment: str,
    from_room: int,
    to_room: int,
    module: str,
    card_id: str,
) -> str:
    fn = _fn_name(segment)
    edge_id = _snake(segment)
    return f"""
## Tip-extension checklist (planner / follow-up cards)

| Step | Action | Owner |
|------|--------|-------|
| 1 | Pure controller `{fn}` in `routes/kpdr/{module}.py` + `KPDR_SEGMENTS` | Luna (this scaffold) |
| 2 | `DoorEdge` `{edge_id}` in `progression.py` (`verification=controller_dev` after pure green) | Luna / planner |
| 3 | Split id + optional `ContinuousTip` in `catalog.py` | Luna (after pure) |
| 4 | `SpineHop` + `TipSegment` in spine; TipSpec generates | Luna (after pure) |
| 5 | `run_to()` + `register_continuous_segments` | Luna (after pure) |
| 6 | `scripts/record/continuous.py --to <tip> --no-video` | **Planner** |
| 7 | STATUS / tracker promote | **Planner** only |

Rooms: 0x{from_room:04X} → 0x{to_room:04X}
Card: {card_id}

Graph pure-gate helper (from Python):
```python
from super_metroid.progression import SPEED_GRAPH, capabilities_from_state
# gate = SPEED_GRAPH.pure_gate(0x{from_room:04X}, 0x{to_room:04X}, caps)
# work = SPEED_GRAPH.suggest_pure_work(0x{from_room:04X}, capabilities=caps)
```
"""


def _register_snippet(segment: str, module: str) -> str:
    fn = _fn_name(segment)
    key = _snake(segment)
    return (
        f'from super_metroid.routes.kpdr.{module} import {fn}\n'
        f'# In KPDR_SEGMENTS:\n'
        f'    "{key}": {fn},\n'
    )


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--segment", required=True, help="Segment id (snake or kebab)")
    p.add_argument(
        "--from-room",
        type=lambda s: int(s, 0),
        required=True,
        help="Entry room id (0x… or int)",
    )
    p.add_argument(
        "--to-room",
        type=lambda s: int(s, 0),
        required=True,
        help="Exit room id (0x… or int)",
    )
    p.add_argument(
        "--module",
        default="k4_norfair",
        help="kpdr module stem (default k4_norfair)",
    )
    p.add_argument(
        "--card-id",
        default="",
        help="Task card id (default SM-SCAFFOLD-<SEGMENT>)",
    )
    p.add_argument(
        "--write",
        action="store_true",
        help="Write module stub + residual card (default dry-run print only)",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Force print-only even with --write",
    )
    p.add_argument(
        "--register",
        action="store_true",
        help="Also append KPDR_SEGMENTS entry when --write (careful)",
    )
    args = p.parse_args()

    segment = _snake(args.segment)
    card_id = args.card_id or f"SM-SCAFFOLD-{segment.upper().replace('_', '-')}"
    module_path = KPDR / f"{args.module}.py"
    residual_path = TASKS / f"{card_id}.md"
    write = args.write and not args.dry_run

    stub = _controller_stub(
        segment=segment,
        from_room=args.from_room,
        to_room=args.to_room,
        module=args.module,
    )
    residual = _residual_md(
        card_id=card_id,
        segment=segment,
        from_room=args.from_room,
        to_room=args.to_room,
        module=args.module,
    )
    checklist = _checklist(
        segment=segment,
        from_room=args.from_room,
        to_room=args.to_room,
        module=args.module,
        card_id=card_id,
    )
    reg = _register_snippet(segment, args.module)

    print("=== controller stub ===")
    print(stub)
    print("=== registry snippet ===")
    print(reg)
    print(checklist)

    if not write:
        print(f"[dry-run] would write {module_path}")
        print(f"[dry-run] would write {residual_path}")
        return

    text = _ensure_module_header(module_path)
    fn = _fn_name(segment)
    if f"def {fn}(" in text:
        print(f"skip controller: {fn} already in {module_path}")
    else:
        # Ensure imports exist for require_room/hold when appending to existing.
        if "require_room" not in text:
            text = text.rstrip() + (
                "\nfrom super_metroid.routes.controller_common import hold, require_room\n"
            )
        if "ControllerSession" not in text:
            text = text.rstrip() + (
                "\nfrom super_metroid.routes.runtime import ControllerSession\n"
            )
        if "SuperMetroidState" not in text:
            text = text.rstrip() + (
                "\nfrom super_metroid.ram import SuperMetroidState\n"
            )
        module_path.write_text(text.rstrip() + "\n" + stub, encoding="utf-8")
        print(f"wrote {module_path.relative_to(ROOT)}")

    if residual_path.is_file():
        print(f"skip residual: exists {residual_path}")
    else:
        residual_path.write_text(residual, encoding="utf-8")
        print(f"wrote {residual_path.relative_to(ROOT)}")

    if args.register:
        reg_text = REGISTRY.read_text(encoding="utf-8")
        key = segment
        if f'"{key}"' in reg_text:
            print(f"skip registry: {key} already registered")
        else:
            import_line = (
                f"from super_metroid.routes.kpdr.{args.module} import {fn}\n"
            )
            if import_line not in reg_text:
                # Insert import near other kpdr imports (before SegmentFn).
                marker = "SegmentFn = Callable"
                if marker in reg_text:
                    reg_text = reg_text.replace(marker, import_line + "\n" + marker)
                else:
                    reg_text = import_line + reg_text
            entry = f'    "{key}": {fn},\n'
            close = "\n}\n\n\ndef get_segment"
            if close in reg_text:
                reg_text = reg_text.replace(close, "\n" + entry + "}\n\n\ndef get_segment")
            else:
                print("warn: could not find KPDR_SEGMENTS close; print entry only")
                print(entry)
            REGISTRY.write_text(reg_text, encoding="utf-8")
            print(f"updated {REGISTRY.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
