"""Planning node ids for Zelda I L3–L9.

Screen / TF constants live in ``zelda_i.anchors`` (canonical). This module
re-exports them and defines NamedRoute graph node string ids.

**Not all route-ready.** Hypothesized entrances stay ``verified=False`` in
``anchors.ENTRANCES``. Do not import source hyps into Clean STATUS claims.
"""

from __future__ import annotations

from zelda_i.anchors import (
    DOOR_SCREEN_BY_LEVEL,
    ENTRANCES,
    FULL_TRIFORCE,
    LATER_SCREEN_LABELS,
    SCREEN_BRACELET_ARMOS,
    SCREEN_CANDLE_SHOP,
    SCREEN_LADDER_HEART,
    SCREEN_LEVEL3_ENTRANCE,
    SCREEN_LEVEL3_ENTRY_ROOM,
    SCREEN_LEVEL4_ENTRANCE,
    SCREEN_LEVEL4_ENTRY_ROOM,
    SCREEN_LEVEL4_RAFT_DOCK,
    SCREEN_LEVEL5_ENTRANCE,
    SCREEN_LEVEL5_ENTRY_ROOM,
    SCREEN_LEVEL5_LOST_HILLS,
    SCREEN_LEVEL6_ENTRANCE,
    SCREEN_LEVEL6_ENTRY_ROOM,
    SCREEN_LEVEL7_BAIT_SHOP,
    SCREEN_LEVEL7_ENTRANCE,
    SCREEN_LEVEL8_BUSH,
    SCREEN_LEVEL8_ENTRANCE,
    SCREEN_LEVEL9_ENTRANCE,
    SCREEN_MAGICAL_SWORD_GRAVE,
    SCREEN_RAFT_HEART_DOCK,
    TF_BIT_L1,
    TF_BIT_L2,
    TF_BIT_L3,
    TF_BIT_L4,
    TF_BIT_L5,
    TF_BIT_L6,
    TF_BIT_L7,
    TF_BIT_L8,
    TF_BITS_ALL,
    TRIFORCE_BITS_BY_LEVEL,
)

# --- Named graph nodes ---
NODE_LEVEL3_ENTRANCE = "ow_74_level3"
NODE_LEVEL3_DUNGEON = "dungeon_level3"
NODE_LEVEL3_ENTRY_ROOM = f"level3_room_{SCREEN_LEVEL3_ENTRY_ROOM:02x}"
NODE_LEVEL3_WEST_KEY = "level3_west_key"
NODE_LEVEL3_RAFT = "level3_raft"
NODE_LEVEL3_BOSS = "level3_manhandla"
NODE_LEVEL3_TF_ROOM = "level3_room_3d"
NODE_LEVEL3_COMPLETE = "level3_triforce_shard_3"

NODE_LEVEL4_ENTRANCE = "ow_45_level4"
NODE_LEVEL4_DUNGEON = "dungeon_level4"
NODE_LEVEL4_ENTRY_ROOM = f"level4_room_{SCREEN_LEVEL4_ENTRY_ROOM:02x}"
NODE_LEVEL4_STEPLADDER = "level4_stepladder"
NODE_LEVEL4_BOSS = "level4_gleeok"
NODE_LEVEL4_TF_ROOM = "level4_room_03"
NODE_LEVEL4_COMPLETE = "level4_triforce_shard_4"

NODE_LEVEL5_ENTRANCE = "ow_0b_level5"
NODE_LEVEL5_DUNGEON = "dungeon_level5"
NODE_LEVEL5_ENTRY_ROOM = f"level5_room_{SCREEN_LEVEL5_ENTRY_ROOM:02x}"
NODE_LEVEL5_KEY_66 = "level5_room_66"
NODE_LEVEL5_EAST_77 = "level5_room_77"
NODE_LEVEL5_WHISTLE = "level5_whistle"
NODE_LEVEL5_BOSS = "level5_digdogger"
NODE_LEVEL5_TF_ROOM = "level5_room_14"
NODE_LEVEL5_COMPLETE = "level5_triforce_shard_5"

NODE_LEVEL6_ENTRANCE = "ow_22_level6"
NODE_LEVEL6_DUNGEON = "dungeon_level6"
NODE_LEVEL6_COMPLETE = "level6_triforce_shard_6"

NODE_LEVEL7_ENTRANCE = "ow_42_level7"
NODE_LEVEL7_DUNGEON = "dungeon_level7"
NODE_LEVEL7_COMPLETE = "level7_triforce_shard_7"

NODE_LEVEL8_ENTRANCE = "ow_6d_level8"
NODE_LEVEL8_DUNGEON = "dungeon_level8"
NODE_LEVEL8_COMPLETE = "level8_triforce_shard_8"

NODE_LEVEL9_ENTRANCE = "ow_05_level9"
NODE_LEVEL9_DUNGEON = "dungeon_level9"
NODE_LEVEL9_ROOM_41 = "level9_room_41"
NODE_LEVEL9_ROOM_31 = "level9_room_31"
NODE_LEVEL9_ROOM_30 = "level9_room_30"
NODE_LEVEL9_CELLAR_67 = "level9_room_67"
NODE_LEVEL9_ROOM_04 = "level9_room_04"
NODE_LEVEL9_ROOM_03 = "level9_room_03"
NODE_LEVEL9_PATRA = "level9_patra"
NODE_LEVEL9_GANON = "level9_ganon"
NODE_LEVEL9_ZELDA = "level9_zelda_ending"

# Optional OW prep nodes (planning)
NODE_BRACELET_ARMOS = "ow_24_bracelet_armos"
NODE_MAGICAL_SWORD = "ow_21_magical_sword"
NODE_BAIT_SHOP = "ow_34_bait_shop"
NODE_CANDLE_SHOP = "ow_5e_candle_shop"
NODE_WHISTLE_POND = "ow_42_whistle_pond"
NODE_LOST_HILLS = "ow_1b_lost_hills"
NODE_RAFT_L4_DOCK = "ow_55_raft_dock_l4"

__all__ = [
    "DOOR_SCREEN_BY_LEVEL",
    "ENTRANCES",
    "FULL_TRIFORCE",
    "LATER_SCREEN_LABELS",
    "NODE_BAIT_SHOP",
    "NODE_BRACELET_ARMOS",
    "NODE_CANDLE_SHOP",
    "NODE_LEVEL3_BOSS",
    "NODE_LEVEL3_COMPLETE",
    "NODE_LEVEL3_DUNGEON",
    "NODE_LEVEL3_ENTRANCE",
    "NODE_LEVEL3_ENTRY_ROOM",
    "NODE_LEVEL3_RAFT",
    "NODE_LEVEL3_TF_ROOM",
    "NODE_LEVEL3_WEST_KEY",
    "NODE_LEVEL4_BOSS",
    "NODE_LEVEL4_COMPLETE",
    "NODE_LEVEL4_DUNGEON",
    "NODE_LEVEL4_ENTRANCE",
    "NODE_LEVEL4_ENTRY_ROOM",
    "NODE_LEVEL4_STEPLADDER",
    "NODE_LEVEL4_TF_ROOM",
    "NODE_LEVEL5_BOSS",
    "NODE_LEVEL5_COMPLETE",
    "NODE_LEVEL5_DUNGEON",
    "NODE_LEVEL5_EAST_77",
    "NODE_LEVEL5_ENTRANCE",
    "NODE_LEVEL5_ENTRY_ROOM",
    "NODE_LEVEL5_KEY_66",
    "NODE_LEVEL5_TF_ROOM",
    "NODE_LEVEL5_WHISTLE",
    "NODE_LEVEL6_COMPLETE",
    "NODE_LEVEL6_DUNGEON",
    "NODE_LEVEL6_ENTRANCE",
    "NODE_LEVEL7_COMPLETE",
    "NODE_LEVEL7_DUNGEON",
    "NODE_LEVEL7_ENTRANCE",
    "NODE_LEVEL8_COMPLETE",
    "NODE_LEVEL8_DUNGEON",
    "NODE_LEVEL8_ENTRANCE",
    "NODE_LEVEL9_CELLAR_67",
    "NODE_LEVEL9_DUNGEON",
    "NODE_LEVEL9_ENTRANCE",
    "NODE_LEVEL9_GANON",
    "NODE_LEVEL9_PATRA",
    "NODE_LEVEL9_ROOM_03",
    "NODE_LEVEL9_ROOM_04",
    "NODE_LEVEL9_ROOM_30",
    "NODE_LEVEL9_ROOM_31",
    "NODE_LEVEL9_ROOM_41",
    "NODE_LEVEL9_ZELDA",
    "NODE_LOST_HILLS",
    "NODE_MAGICAL_SWORD",
    "NODE_RAFT_L4_DOCK",
    "NODE_WHISTLE_POND",
    "SCREEN_BRACELET_ARMOS",
    "SCREEN_CANDLE_SHOP",
    "SCREEN_LADDER_HEART",
    "SCREEN_LEVEL3_ENTRANCE",
    "SCREEN_LEVEL3_ENTRY_ROOM",
    "SCREEN_LEVEL4_ENTRANCE",
    "SCREEN_LEVEL4_ENTRY_ROOM",
    "SCREEN_LEVEL4_RAFT_DOCK",
    "SCREEN_LEVEL5_ENTRANCE",
    "SCREEN_LEVEL5_ENTRY_ROOM",
    "SCREEN_LEVEL5_LOST_HILLS",
    "SCREEN_LEVEL6_ENTRANCE",
    "SCREEN_LEVEL6_ENTRY_ROOM",
    "SCREEN_LEVEL7_BAIT_SHOP",
    "SCREEN_LEVEL7_ENTRANCE",
    "SCREEN_LEVEL8_BUSH",
    "SCREEN_LEVEL8_ENTRANCE",
    "SCREEN_LEVEL9_ENTRANCE",
    "SCREEN_MAGICAL_SWORD_GRAVE",
    "SCREEN_RAFT_HEART_DOCK",
    "TF_BIT_L1",
    "TF_BIT_L2",
    "TF_BIT_L3",
    "TF_BIT_L4",
    "TF_BIT_L5",
    "TF_BIT_L6",
    "TF_BIT_L7",
    "TF_BIT_L8",
    "TF_BITS_ALL",
    "TRIFORCE_BITS_BY_LEVEL",
]
